/*
 * File: app/controller/TbButtonController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('I_MAT_STOCK_HSPF.controller.TbButtonController', {
	extend : 'Ext.app.Controller',
	stores: ['MyStore'],
	
	control : {
		"#selBtn" : {
			click : 'selBtnClick'
		},
		"#saveBtn" : {
			click : 'saveBtnClick'
		},
		"#delBtn" : {
			click : 'delBtnClick'
		},
		"#clsBtn" : {
			click : 'clsBtnClick'
		},
		"mysearchform textfield[name=search_field]" : {
			specialkey : 'tfEnter'
		}
	},

	selBtnClick : function(button, e, eOpts) {
		var store = this.getMyStoreStore();
		store.removeAll();
		store.load({
			params : {
				V_TYPE : 'S',
				V_STOCK_DT : Ext.getCmp('V_STOCK_DT').getValue(),
				V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
				V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
			},
			callback : function(records, operations, success) {
				
			}
		})
	},

	saveBtnClick : function(button, e, eOpts) {
		var store = this.getMyStoreStore();
		var gridRecord = Ext.getCmp('myGrid').getSelectionModel().getSelection();
		
		var selModel= Ext.getCmp('myGrid').getSelectionModel();
		selModel.selectAll();
		
		store.each(function(record, idx){
			if(record.crudState == 'C') {
				record.set('V_TYPE', 'I');
			} else if(record.crudState == 'U') {
				record.set('V_TYPE', 'U');
			}
		});
		
		store.sync({
			params: {
				V_TYPE: 'SYNC',
				V_COMP_ID: parent.Ext.getCmp('GCOMP_ID').getValue(),
				V_USR_ID: parent.Ext.getCmp('GUSER_ID').getValue(),
				V_STOCK_DT: Ext.getCmp('V_STOCK_DT').getValue(),
			},
			callback: function() {
				var tbController = I_MAT_STOCK_HSPF.app.getController("TbButtonController");
				tbController.selBtnClick();
			}
		});
	},

	delBtnClick : function(button, e, eOpts) {},

	clsBtnClick : function(button, e, eOpts) {
		alert('close');
	},

	tfEnter : function(field, e, eOpts) {
		if (e.getKey() == e.ENTER) {
			this.selBtnClick();
		}
	}

});
