/*
 * File: app/view/AsnPop.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SUPP_DLV_TOT_HSPF.view.AsnPop', {
    extend: 'Ext.window.Window',
    alias: 'widget.asnpop',

    requires: [
        'SUPP_DLV_TOT_HSPF.view.AsnPopViewModel',
        'SUPP_DLV_TOT_HSPF.view.AsnPopViewController',
        'SUPP_DLV_TOT_HSPF.view.MySearchForm1',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.Exporter',
        'Ext.grid.column.Date',
        'Ext.grid.plugin.Clipboard',
        'Ext.grid.plugin.CellEditing'
    ],

    controller: 'asnpop',
    viewModel: {
        type: 'asnpop'
    },
    modal: true,
    height: 800,
    width: 1280,
    title: 'ASN팝업',

    id: 'asnpop',
    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'mysearchform1'
        },
        {
            xtype: 'container',
            flex: 0.3,
            height: 204,
            layout: 'fit',
            items: [
                {
                    xtype: 'gridpanel',
                    columnLines: true, 
                    id: 'myGrid2',
                    style: 'border: 1px solid lightgray; padding: 5px;',
                    bodyBorder: false,
                    header: false,
                    store: 'MyStore2',
                    
                    
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 40,
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            text: 'V_TYPE',
                            dataIndex: 'V_TYPE'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 150,
                            dataIndex: 'ASN_NO',
                            text: 'ASN번호'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            dataIndex: 'ASN_STS_NM',
                            text: 'ASN상태'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            dataIndex: 'PO_NO',
                            width: 150,
                            text: '발주번호'
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'end',
                            dataIndex: 'PO_SEQ',
                            text: '발주순번',
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 85,
                            dataIndex: 'CFM_YN',
                            text: '확정유무',
                            align: 'center'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 150,
                            dataIndex: 'ITEM_CD',
                            text: '품목코드'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            dataIndex: 'BP_ITEM_CD',
                            text: '고객사<br>품목코드'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 200,
                            dataIndex: 'ITEM_NM',
                            text: '품목명'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 130,
                            dataIndex: 'SPEC',
                            text: '규격'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 85,
                            dataIndex: 'UNIT',
                            text: '단위'
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 120,
                            align: 'right',
                            dataIndex: 'BAR_NO_PRINT',
                            text: '바코드<br>미발행수',
                            format: '0,000.00'
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 90,
                            align: 'right',
                            dataIndex: 'QTY',
                            text: '수량',
                            format: '0,000.00'
                        },
                        {
                            xtype: 'datecolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            dataIndex: 'DLVY_AVL_DT',
                            format: 'Y-m-d',
                            text: '납품가능일',
                            align: 'center'
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'right',
                            dataIndex: 'GR_QTY',
                            text: '입고수량',
                            format: '0,000.00'
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'gridexporter'
                        }
                    ],
                    selModel: {
                        selType: 'rowmodel'
                    },
	                  viewConfig: {
	                  	enableTextSelection: true,
	                  	getRowClass: function(record, index) {
	                        var CFM_YN = record.get('CFM_YN');
	                        if(CFM_YN == 'Y') {
	                        	return 'bg-green'
	                        }
	                    },
	                }
                }
            ]
        },
        {
        	xtype: 'splitter',
        	collapseTarget: 'prev'
        },
        {
            xtype: 'container',
            flex: 0.7,
            layout: 'fit',
            items: [
                {
                    xtype: 'gridpanel',
                    tbar: [
                           {
                               id: 'gridAddBtn_W',
                               text: '',
                               margin: '0 3 0 0',
                               glyph: 'xf055@FontAwesome',
                               iconCls: 'grid-add-btn',
                               hidden: true
//                               disabled: true
                           },
                           {
                               id: 'gridDelBtn_W',
                               text: '',
                               margin: '0 3 0 0',
                               glyph: 'xf056@FontAwesome',
                               iconCls: 'grid-del-btn',
                               hidden: true
//                           	disabled: true
                           },
                           {
                           	id: 'bacdSaveBtn',
                           	xtype: 'button',
                           	margin: '0 2 0 0',
                           	text: '바코드추가',
                               hidden: true
                           },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                        	xtype: 'checkboxfield',
                        	boxLabel: '로트정보일괄등록',
                        	id: 'chk',
                        	margin: '0 10 0 0',
                        	value: false,
                        	listeners: {
                                click: {
                                    element: 'el', //bind to the underlying el property on the panel
                                    fn: function (id) {
                                		var store2 = Ext.getStore('MyStore2');
                                    	var store3 = Ext.getStore('MyStore3');
                                    	var chkValue = Ext.getCmp('chk').getValue();
                                    	var LOT_NO = '';
                                    	var MAKE_DT = '';
                                    	var VALID_DT = '';
                                    	var flag = ''; //확정확인용
                                    	var flag2 = ''; //로트일부변경용
                                    	
                                    	//확정확인
                                    	store2.each(function(record,idx){
                                			if(record.get('CFM_YN') == 'N') {
                                				flag = 'T';
                                			} else {
                                				flag = 'F';
                                			}
                                    	});
                                    	
                                    	//일부변경확인
                                    	var gridRecord3 = Ext.getCmp('myGrid3').getSelectionModel().getSelection();
                                    	
                                    	if (parent.Ext.getCmp('GBP_CD').getValue() == '00000' ) {
                                    		flag = 'T';
                                    	}
                                    	
                                    	for(var i=0; i<gridRecord3.length; i++) {
                                    		if(gridRecord3[i].data['LOT_NO'] != null && gridRecord3[i].data['LOT_NO']  != undefined && gridRecord3[i].data['LOT_NO'] != ''){
                                    			LOT_NO = gridRecord3[i].data['LOT_NO'];
                                    			MAKE_DT = gridRecord3[i].data['MAKE_DT'];
                                    			VALID_DT = gridRecord3[i].data['VALID_DT'];
                                    			break;
                                    		}
                                    	}
                                    	
                                    	if(flag == 'T') { //확정취소 상태일 때만..
                                			if(chkValue == true) { 
                                        		for(var i=0; i<gridRecord3.length; i++) {
                                        			if(gridRecord3[i].data['LOT_CHECK'] == 'Y') {
                                        				gridRecord3[i].set('LOT_NO', LOT_NO);
                                        				gridRecord3[i].set('MAKE_DT', MAKE_DT);
                                        				gridRecord3[i].set('VALID_DT', VALID_DT);
                                        			}
                                        		}
                                			}
                                    	}
                                	}
                                },
                        	}
                        },
                        {
                            id: 'refreshBtn',
                            xtype: 'button',
            	            glyph: 'xf021@FontAwesome',
                        	iconCls: 'grid-refresh-btn',
            	            margin: '0 2 0 0'
                        },
                        {
                        	id: 'lotSaveBtn',
                        	xtype: 'button',
                        	glyph: 'xf0c7@FontAwesome',
                        	iconCls: 'grid-save-btn',
                        	margin: '0 2 0 0'
                        },
                        {
                        	id: 'grdnBtn',
                        	xtype: 'button',
                        	margin: '0 2 0 0',
                        	text: '입출고등록',
                        	hidden: true
                        },
                        {
                            xtype: 'button',
                            glyph: 'xf1c3@FontAwesome',
                            id: 'xlsxDown3',
                            cfg: {
                                type: 'excel07',
                                ext: 'xlsx'
                            },
                            iconCls: 'grid-excel-btn',
                        }
                    ],
                    id: 'myGrid3',
                    style: 'border: 1px solid lightgray; padding: 5px;',
                    header: false,
                    store: 'MyStore3',
                    columnLines: true, 
                    columns: [
                        {
                            xtype: 'rownumberer',
//                            locked: true,
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 73,
                            text: '순번',
                            dataIndex: 'ASN_SEQ',
                            align: 'right',
                            hidden: true
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
                        	text: '발주번호',
                        	dataIndex: 'PO_NO',
                        	width: 150,
                        	hidden: true
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
                        	text: '발주순번',
                        	dataIndex: 'PO_SEQ',
                        	width: 150,
                        	hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            text: '품목코드',
                            dataIndex: 'ITEM_CD',
                            width: 150
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            text: '품목명',
                            dataIndex: 'ITEM_NM',
                            width: 200
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            text: '팔레트',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    width: 68,
                                    text: '순번',
                                    dataIndex: 'PAL_BC_SEQ',
                                    align: 'right',
                                    hidden: true
                                },
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    width: 190,
                                    text: '팔레트 바코드번호',
                                    dataIndex: 'PAL_BC_NO',
                                    
                                },
                                {
                                    xtype: 'numbercolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    width: 90,
                                    text: '납품수량',
                                    dataIndex: 'PAL_QTY',
                                    format: '0,000.00',
                                    align: 'right'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            text: '박스',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    width: 68,
                                    text: '순번',
                                    dataIndex: 'BOX_BC_SEQ',
                                    format: '0,000',
                                    align: 'right',
                                    hidden: true
                                },
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    width: 190,
                                    text: '박스 바코드번호',
                                    dataIndex: 'BOX_BC_NO'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    width: 90,
                                    text: '납품수량',
                                    dataIndex: 'BOX_QTY',
                                    format: '0,000.00',
                                    align: 'right'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            text: '로트',
                            columns: [
								{
								    xtype: 'gridcolumn',
								    style: 'font-size: 12px; text-align: center; font-weight: bold;',
								    width: 90,
								    text: '순번',
								    align: 'right',
								    dataIndex: 'LOT_BC_SEQ',
		                            hidden: true
								},
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    width: 190,
                                    text: '로트바코드번호',
                                    dataIndex: 'LOT_BC_NO'
                                },
                                {
                                	xtype: 'gridcolumn',
                                	style: 'font-size: 12px; text-align: center; font-weight: bold;  color: #3367d6',
                                	width: 124,
                                	text: '<span style=\'color:red\'>*</span>로트번호',
                                	dataIndex: 'LOT_NO',
                                    editor: {
                                    	xtype: 'textfield'
                                    },
                                    
                                },
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;  color: #3367d6',
                                    text: '<span style=\'color:red\'>*</span>제조일',
                                    dataIndex: 'MAKE_DT',
                                    format:'Y-m-d',
                                    editor: {
                                    	xtype: 'datefield',
                                    	format: 'Y-m-d',
                                        allowBlank: false,
                                    },
                                    align: 'center',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        return Ext.util.Format.date(value,'Y-m-d');
                                    },
                                    emptyCellText: 'YYYY-MM-DD',
                                    width: 130,
                                },
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;  color: #3367d6',
                                    text: '<span style=\'color:red\'>*</span>유효일',
                                    dataIndex: 'VALID_DT',
                                    editor: {
                                    	xtype: 'datefield',
                                    	format: 'Y-m-d',
                                        allowBlank: false,
                                    },
                                    align: 'center',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        return Ext.util.Format.date(value,'Y-m-d');
                                    },
                                    emptyCellText: 'YYYY-MM-DD',
                                    width: 130,
                                },
                                {
                                    xtype: 'numbercolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                                    width: 102,
                                    text: '납품수량',
                                    dataIndex: 'LOT_QTY',
                                    format: '0,000.00',
                                    align: 'right',
                                    editor: {
                                    	xtype: 'numberfield',
                                    	minValue: 0
                                    }
                                },
                                {
                                	xtype: 'gridcolumn',
                                	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                                	width: 50,
                                	dataIndex: 'LOT_CHECK',
                                	align: 'center',
                                	id: 'LOT_CHECK',
                                	hidden: true
                                },
                            ],
                        },
                        {
                        	xtype: 'numbercolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 102,
                        	text: '입고수량',
                        	dataIndex: 'GR_QTY',
                        	format: '0,000.00',
                        	align: 'right',
                        	hidden: true,
                        	id: 'G_GR_QTY',
                            tdCls: 'x-change-cell1' 	,
                            editor: {
                            	xtype: 'numberfield',
                            	minValue: 0,
                            }
                        },
                        {
                        	xtype: 'numbercolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 102,
                        	text: '출고수량',
                        	dataIndex: 'DN_QTY',
                        	format: '0,000.00',
                        	align: 'right',
                        	hidden: true,
                        	id: 'G_DN_QTY',
                            tdCls: 'x-change-cell2' 	,
                            editor: {
                            	xtype: 'numberfield',
                            	minValue: 0
                            }
                        },
                    ],
                    plugins: [
							  {
							      ptype: 'gridexporter'
							  },
                              {
                                  ptype: 'clipboard'
                              },
                              {
                                  ptype: 'cellediting',
                                  clicksToEdit: 2,
                                  listeners: {
                                  	edit: function(editor, context, eOpts) {
                                  		var selModel= Ext.getCmp('myGrid3').getSelectionModel();
                                  		selModel.select(context.record, true);
                                  	},
                                	  	beforeedit: function(editor, context, eOpts) {
                                	  	//확정된 항목은 수정할 수 없음.
                                	  		var store2 = Ext.getStore('MyStore2');
                                	  		var flag = '';
                                	  		store2.each(function(record,idx){
                            	    			if(record.get('CFM_YN') == 'N') {
                            	    				flag = 'T';
                            	    			} else {
                            	    				flag = 'F';
                            	    				return false;
                            	    			}
                                	    	});
                                	  		
                                	  		if(((flag == 'F') && (parent.Ext.getCmp('GBP_CD').getValue() != '00000')) 
                          					 && (context.field == 'VALID_DT' 
                          						 || context.field == 'MAKE_DT'
                      							 || context.field == 'LOT_NO'
                          					     || context.field == 'LOT_QTY' )) {
                          					context.cancel = true; 
                          				}
                                	  		
                                	  		var lot_qty = context.record.get('LOT_QTY');
                                	  		
                                	  		if(context.field == 'GR_QTY') {
                                	  			context.record.set('GR_QTY', lot_qty);
                                	  		} else if(context.field == 'DN_QTY') {
                                	  			context.record.set('DN_QTY', lot_qty);
                                	  		}
                                	  	},
                                 }
                              }
                          ],
                  viewConfig: {
                  	enableTextSelection: true,
                    getRowClass: function(record, index) {
                        var GR_QTY = Number(record.get('GR_QTY'));
                        var DN_QTY = Number(record.get('DN_QTY'));
                        
                        if (GR_QTY > 0) { //납품가능수량이 0보다 작다.
                        	if (DN_QTY > 0) {
                            	return 'qty-style2';
                            } else {
                            	return 'qty-style1';
                            }
                        } 
                        
                    },
                },
                  selModel: {
                      selType: 'checkboxmodel',
                      injectCheckbox: 'last',
                      listeners: {
                      	select: function(rowmodel, record, index, eOpts) {
                          	record.set('LOT_CHECK', 'Y');
                          },
                          deselect: function(rowmodel, record, index, eOpts) {
                          	record.set('LOT_CHECK', '');
                          }
                      },
                  },
                }
            ]
        }
    ]

});