/*
 * File: app/controller/TbButtonController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('S_BL_DOC_TOT_HSPF.controller.TbButtonController', {
    extend: 'Ext.app.Controller',

    stores: ['MyStore', 'MyStore1', 'MyStore2', 'TradeInfoStore', 'ItemStore','PopStore', 'PopStore2'],
    control: {
        "#selBtn": {
            click: 'selBtnClick'
        },
        "#saveBtn": {
            click: 'saveBtnClick'
        },
        "#delBtn": {
            click: 'delBtnClick'
        },
        "#dnHistBtn": {
            click: 'dnHistBtnClick'
        },
        "#cfmBtn": {
            click: 'cfmBtnClick'
        },
        "#clsBtn": {
            click: 'clsBtnClick'
        },
        "#clrBtn": {
            click: 'clrBtnClick'
        },
        "myviewport textfield[name=search_field]": {
            specialkey: 'tfEnter'
        },
        
        "#printInv1Btn": {
            click: 'printInvBtnClick'
        },
        "#printInv2Btn": {
            click: 'printInvBtnClick'
        },
        "#printInv3Btn": {
            click: 'printInvBtnClick'
        },
        "#printInv4Btn": {
            click: 'printInvBtnClick'
        },
        "#printInv5Btn": {
            click: 'printInvBtnClick'
        },
        "#printInv6Btn": {
            click: 'printInvBtnClick'
        },
    },

    selBtnClick: function(button, e, eOpts) {
    	var store1 = this.getMyStore1Store();
    	var store2 = this.getMyStore2Store();
//    	var activeTab = Ext.getCmp('myTab').getActiveTab().xtype;
    	
//    	if(activeTab === 'mypanel'){
	    	Ext.Ajax.request({
				url : 'sql/S_BL_DOC_TOT_HSPF.jsp',
				method : 'post',
				params : {
					V_TYPE : 'T1S',
					V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
					V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
					V_INV_NO: Ext.getCmp('V_INV_NO').getValue(),
				},
				success : function(response) {
					var res = Ext.JSON.decode(response.responseText).resultList[0];
	
					if(!!res){
						Ext.getCmp('V_BP_NM').setValue(res.BP_NM);
						Ext.getCmp('V_BP_CD').setValue(res.BP_CD);
						
				    	Ext.getCmp('V_INV_NO').setValue(res.INV_NO);
				    	Ext.getCmp('V_INVOICE_NO').setValue(res.INVOICE_NO);
				    	Ext.getCmp('V_INV_DT').setValue(res.INV_DT);
				    	Ext.getCmp('V_LC_DOC_NO').setValue(res.LC_DOC_NO);
				    	Ext.getCmp('V_LC_DT').setValue(res.LC_DT);
				    	Ext.getCmp('V_BL_DOC_NO').setValue(res.BL_DOC_NO);
				    	Ext.getCmp('V_LOADING_DT').setValue(res.LOADING_DT);
				    	
				    	Ext.getCmp('V_CONSIGNEE').setValue(res.CONSIGNEE);
				    	Ext.getCmp('V_BUYER_ADDR').setValue(res.BUYER_ADDR);
				    	Ext.getCmp('V_SHIP_MARK').setValue(res.SHIP_MARK);
				    	Ext.getCmp('V_NOTIFY').setValue(res.NOTIFY);
//				    	Ext.getCmp('V_GOAL_NM').setValue(res.GOAL_NM);
				    	Ext.getCmp('V_TRANS_TYPE').setValue(res.TRANS_TYPE);
				    	Ext.getCmp('V_VESSEL').setValue(res.VESSEL);
				    	Ext.getCmp('V_TITLE').setValue(res.TITLE);
				    	Ext.getCmp('V_PAY_METH').setValue(res.PAY_METH);
				    	Ext.getCmp('V_IN_TERMS').setValue(res.IN_TERMS);
				    	Ext.getCmp('V_LOADING_PORT').setValue(res.LOADING_PORT);
				    	Ext.getCmp('V_DISCHGE_PORT').setValue(res.DISCHGE_PORT);
//				    	Ext.getCmp('V_CNTR_NO').setValue(res.CNTR_NO);
				    	Ext.getCmp('V_TERMINAL').setValue(res.TERMINAL);
				    	Ext.getCmp('V_INSUR_AMT').setValue(res.INSUR_AMT);
				    	Ext.getCmp('V_CNTR_QTY').setValue(res.CNTR_QTY);
				    	Ext.getCmp('V_CNTR_SZTP').setValue(res.CNTR_SZTP);
				    	Ext.getCmp('V_CUR').setValue(res.CUR);
//				    	Ext.getCmp('V_PAY_CONDITION').setValue(res.PAY_CONDITION);
				    	Ext.getCmp('V_ETD').setValue(res.ETD);
//				    	Ext.getCmp('V_ETA').setValue(res.ETA);
				    	Ext.getCmp('V_SELLER').setValue(res.SELLER);
				    	Ext.getCmp('V_CFM_YN').setValue(res.CFM_YN);
				    	Ext.getCmp('V_REMARK').setValue(res.REMARK);
				    	
			    		// [두번째 탭] 조회
				    	store1.removeAll();
			        	store1.load({
			        		params: {
			        			V_TYPE: 'T2S',
			        			V_COMP_ID: parent.Ext.getCmp('GCOMP_ID').getValue(),
			        			V_USR_ID: parent.Ext.getCmp('GUSER_ID').getValue(),
			        			V_INV_NO: Ext.getCmp('V_INV_NO').getValue(),
			        		},
			        		callback: function(records,operations,success){
			        			
			        		},
			        	});
			    		
			    		// [세번째 탭] 조회
			        	store2.removeAll();
			        	store2.load({
			        		params: {
			        			V_TYPE: 'T3S',
			        			V_COMP_ID: parent.Ext.getCmp('GCOMP_ID').getValue(),
			        			V_USR_ID: parent.Ext.getCmp('GUSER_ID').getValue(),
			        			V_INV_NO: Ext.getCmp('V_INV_NO').getValue(),
			        		},
			        		callback: function(records,operations,success){
			        			
			        		},
			        	});
					}
				}
			});
		
    },

    saveBtnClick: function(button, e, eOpts) {
    	var store1 = Ext.getStore('MyStore1');
    	var store2 = Ext.getStore('MyStore2');
    	var flag = '';
		var msg = '';
		
		if (!!!Ext.getCmp('V_INV_DT').getValue()) {
			flag = 'F';
			msg = 'INV DATE를 입력하세요.';
		} else if (Ext.getCmp('V_CFM_YN').getValue() == 'Y') {
			flag = 'F';
			msg = '확정취소 후 가능합니다.';
		} else {
			flag = 'T';
		}
		
		if (flag == 'T') {
			Ext.Msg.confirm('확인', '저장하시겠습니까?', function(button) {
				if (button == 'yes') {
					S_BL_DOC_TOT_HSPF.app.getController("TbButtonController").setTitle();
					
					Ext.Ajax.request({
						url : 'sql/S_BL_DOC_TOT_HSPF.jsp',
						method : 'post',
						params : {
							V_TYPE : 'IH',
							V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
							V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
							
							V_INV_NO: Ext.getCmp('V_INV_NO').getValue(),
							V_INVOICE_NO: Ext.getCmp('V_INVOICE_NO').getValue(),
							V_INV_DT: Ext.getCmp('V_INV_DT').getValue(),
							V_BP_CD: Ext.getCmp('V_BP_CD').getValue(),
							V_LC_DOC_NO: Ext.getCmp('V_LC_DOC_NO').getValue(),
							V_LC_DT: Ext.getCmp('V_LC_DT').getValue(),
							V_BL_DOC_NO: Ext.getCmp('V_BL_DOC_NO').getValue(),
							V_LOADING_DT: Ext.getCmp('V_LOADING_DT').getValue(),
							V_CONSIGNEE: Ext.getCmp('V_CONSIGNEE').getValue(),
							V_BUYER_ADDR: Ext.getCmp('V_BUYER_ADDR').getValue(),
							V_SHIP_MARK: Ext.getCmp('V_SHIP_MARK').getValue(),
							V_NOTIFY: Ext.getCmp('V_NOTIFY').getValue(),
//							V_GOAL_NM: Ext.getCmp('V_GOAL_NM').getValue(),
							V_TRANS_TYPE: Ext.getCmp('V_TRANS_TYPE').getValue(),
							V_VESSEL: Ext.getCmp('V_VESSEL').getValue(),
							V_TITLE: Ext.getCmp('V_TITLE').getValue(),
							V_PAY_METH: Ext.getCmp('V_PAY_METH').getValue(),
							V_IN_TERMS: Ext.getCmp('V_IN_TERMS').getValue(),
//							V_PAY_CONDITION: Ext.getCmp('V_PAY_CONDITION').getValue(),
							V_DISCHGE_PORT: Ext.getCmp('V_DISCHGE_PORT').getValue(),
							V_LOADING_PORT: Ext.getCmp('V_LOADING_PORT').getValue(),
//							V_CNTR_NO: Ext.getCmp('V_CNTR_NO').getValue(),
							V_TERMINAL: Ext.getCmp('V_TERMINAL').getValue(),
							V_INSUR_AMT: Ext.getCmp('V_INSUR_AMT').getValue(),
							V_CNTR_QTY: Ext.getCmp('V_CNTR_QTY').getValue(),
							V_CNTR_SZTP: Ext.getCmp('V_CNTR_SZTP').getValue(),
							V_CUR: Ext.getCmp('V_CUR').getValue(),
							V_ETD: Ext.getCmp('V_ETD').getValue(),
//							V_ETA: Ext.getCmp('V_ETA').getValue(),
							V_SELLER: Ext.getCmp('V_SELLER').getValue(),
							V_REMARK: Ext.getCmp('V_REMARK').getValue(),
						},
						success : function(response) {
							var INV_NO = response.responseText;
							
							if(!!INV_NO){
								if(store1.data.length > 0){
									
									store1.each(function(rec,idx) {
										if (!!rec.get('INV_NO') && rec.get('V_TYPE') != 'I' && rec.isDirty()) {
											rec.set('V_TYPE', 'U');
										}
									});
									
									store1.sync({ 
										params : {
											V_TYPE : 'SYNC1',
											V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
											V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
											V_INV_NO: INV_NO,
										},
										callback : function(records, operation, success) {
										}, 
									});
									
									store2.each(function(rec,idx) {
										if (!!rec.get('INV_NO') && rec.get('V_TYPE') != 'I' && rec.isDirty()) {
											rec.set('V_TYPE', 'U');
										}
									});
									
									store2.sync({ 
										params : {
											V_TYPE : 'SYNC2',
											V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
											V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
											V_INV_NO: INV_NO,
										},
										callback : function(records, operation, success) {
										}, 
									});
									
									Ext.toast({
										title : ' ',
										timeout : 1000,
										html : '저장완료',
										style : 'text-align: center',
										align : 't',
										width : 130,
									});
									
									Ext.getCmp('V_INV_NO').setValue(INV_NO);
									var tbController = S_BL_DOC_TOT_HSPF.app.getController("TbButtonController");
						    		tbController.selBtnClick();
								} else {
									Ext.toast({
										title : ' ',
										timeout : 1000,
										html : '저장완료',
										style : 'text-align: center',
										align : 't',
										width : 130,
									});
									
									Ext.getCmp('V_INV_NO').setValue(INV_NO);
									var tbController = S_BL_DOC_TOT_HSPF.app.getController("TbButtonController");
						    		tbController.selBtnClick();
								}
								
							}
						}
					});
				}
			});
		} else {
			Ext.Msg.alert('확인', msg);
		}
    	
    },
    
    delBtnClick: function(button, e, eOpts) {
    	var flag = '';
		var msg = '';
		
		if (!!!Ext.getCmp('V_INV_NO').getValue()) {
			flag = 'F';
			msg = '인보이스가 등록되지 않았습니다.';
		} else if (Ext.getCmp('V_CFM_YN').getValue() == 'Y') {
			flag = 'F';
			msg = '확정취소 후 가능합니다.';
		} else {
			flag = 'T';
		}
		
		if (flag == 'T') {
			Ext.Msg.confirm('확인', '삭제하시겠습니까?', function(button) {
				if (button == 'yes') {
					Ext.Ajax.request({
						url : 'sql/S_BL_DOC_TOT_HSPF.jsp',
						method : 'post',
						params : {
							V_TYPE : 'DH',
							V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
							V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
							V_INV_NO: Ext.getCmp('V_INV_NO').getValue(),
						},
						success : function(response) {
							var result = response.responseText;
							
							if(!!result){
								Ext.toast({
									title : ' ',
									timeout : 1000,
									html : '삭제완료',
									style : 'text-align: center',
									align : 't',
									width : 130,
								});
								
								Ext.getCmp('V_INV_NO').setValue(result);
								var tbController = S_BL_DOC_TOT_HSPF.app.getController("TbButtonController");
					    		tbController.clrBtnClick();
							}
						}
					});
				}
			});
		} else {
			Ext.Msg.alert('확인', msg);
		}
    	
    },
    
    cfmBtnClick: function(button, e, eOpts) {
    	var flag = '';
		var msg = '';
		var prcNm = '확정';
		var CFM_YN = 'Y';
		
		if (!!!Ext.getCmp('V_INV_NO').getValue()) {
			flag = 'F';
			msg = '인보이스 등록 후 가능합니다.';
		} else {
			flag = 'T';
		}
		
		if(Ext.getCmp('V_CFM_YN').getValue() == 'Y'){
			prcNm = '확정취소';
			CFM_YN = 'N';
		}
		
		if (flag == 'T') {
			Ext.Msg.confirm('확인', prcNm+' 하시겠습니까?', function(button) {
				if (button == 'yes') {
					Ext.Ajax.request({
						url : 'sql/S_BL_DOC_TOT_HSPF.jsp',
						method : 'post',
						params : {
							V_TYPE : 'CFM',
							V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
							V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
							V_INV_NO: Ext.getCmp('V_INV_NO').getValue(),
							V_CFM_YN: CFM_YN,
						},
						success : function(response) {
							var result = response.responseText;
							
							if(!!result){
								Ext.toast({
									title : ' ',
									timeout : 1000,
									html : prcNm+' 완료',
									style : 'text-align: center',
									align : 't',
									width : 130,
								});
								
								var tbController = S_BL_DOC_TOT_HSPF.app.getController("TbButtonController");
					    		tbController.selBtnClick();
							}
						}
					});
				}
			});
		} else {
			Ext.Msg.alert('확인', msg);
		}
    	
    },

    clsBtnClick: function(button, e, eOpts) {
		var tab = parent.Ext.getCmp('myTab');
		var activeTab = tab.getActiveTab();
		var tabIndex = tab.items.indexOf(activeTab);
		tab.remove(tabIndex, true);
	},
	
	clrBtnClick: function(button, e, eOpts) {
		var store1 = this.getMyStore1Store();
    	var store2 = this.getMyStore2Store();
    	
    	store1.removeAll();
    	store2.removeAll();
    	
    	Ext.getCmp('V_INVOICE_NO').setValue('');
    	Ext.getCmp('V_INV_NO').setValue('');
    	Ext.getCmp('V_INV_DT').setValue('');
    	Ext.getCmp('V_BP_NM').setValue('');
    	Ext.getCmp('V_BP_CD').setValue('');
    	Ext.getCmp('V_LC_DOC_NO').setValue('');
    	Ext.getCmp('V_LC_DT').setValue('');
    	Ext.getCmp('V_BL_DOC_NO').setValue('');
    	Ext.getCmp('V_LOADING_DT').setValue('');
    	
    	Ext.getCmp('V_CONSIGNEE').setValue('');
    	Ext.getCmp('V_BUYER_ADDR').setValue('');
    	Ext.getCmp('V_SHIP_MARK').setValue('');
    	Ext.getCmp('V_NOTIFY').setValue('');
//    	Ext.getCmp('V_GOAL_NM').setValue('');
    	Ext.getCmp('V_TRANS_TYPE').setValue('');
    	Ext.getCmp('V_VESSEL').setValue('');
    	Ext.getCmp('V_TITLE').setValue('');
    	Ext.getCmp('V_PAY_METH').setValue('');
    	Ext.getCmp('V_IN_TERMS').setValue('');
    	Ext.getCmp('V_LOADING_PORT').setValue('');
    	Ext.getCmp('V_DISCHGE_PORT').setValue('');
//    	Ext.getCmp('V_CNTR_NO').setValue('');
    	Ext.getCmp('V_TERMINAL').setValue('');
    	Ext.getCmp('V_INSUR_AMT').setValue('');
    	Ext.getCmp('V_CNTR_QTY').setValue('');
    	Ext.getCmp('V_CNTR_SZTP').setValue('');
    	Ext.getCmp('V_CUR').setValue('');
//    	Ext.getCmp('V_PAY_CONDITION').setValue('');
    	Ext.getCmp('V_ETD').setValue('');
//    	Ext.getCmp('V_ETA').setValue('');
    	Ext.getCmp('V_SELLER').setValue('');
    	Ext.getCmp('V_REMARK').setValue('');
    	Ext.getCmp('V_CFM_YN').setValue('');
	},
	
	dnHistBtnClick : function(button, e, eOpts) {
		if (!!!Ext.getCmp('V_INV_NO').getValue()) {
			Ext.Msg.alert('확인', '인보이스 등록 후 가능합니다.');
			return;
		}
		
		var popup = Ext.create("S_BL_DOC_TOT_HSPF.view.MyWindow");
		popup.center();
//		popup.setSize(Ext.getBody().getViewSize());
        popup.show();
	},

    tfEnter: function(field, e, eOpts) {
        if (e.getKey() == e.ENTER) {
        	this.selBtnClick();
        }
    },
    
    printInvBtnClick : function(button, e, eOpts) {
    	var url = '';
    	var btnId = button.getId();
    	
    	if(btnId == 'printInv1Btn'){
    		url = 'http://123.142.124.170:8080/aireport/on_server/S_BL_INVOICE_TOT_HSPF_A110.jsp?';
    	} else if(btnId == 'printInv2Btn'){
    		url = 'http://123.142.124.170:8080/aireport/on_server/S_BL_INVOICE_TOT_HSPF_BP_A110.jsp?';
    	} else if(btnId == 'printInv3Btn'){
    		url = 'http://123.142.124.170:8080/aireport/on_server/S_BL_PACKING_LIST_TOT_HSPF_A110.jsp?';
    	} else if(btnId == 'printInv4Btn'){
    		url = 'http://123.142.124.170:8080/aireport/on_server/S_BL_INVOICE_TOT_HSPF_A109.jsp?';
    	} else if(btnId == 'printInv5Btn'){
    		url = 'http://123.142.124.170:8080/aireport/on_server/S_BL_PACKING_LIST_TOT_HSPF_A109.jsp?';
    	} else if(btnId == 'printInv6Btn'){
    		url = 'http://123.142.124.170:8080/aireport/on_server/S_BL_PACKING_LIST_TOT_HSPF_BP_A109.jsp?';
    	}
    	
    	if(!!Ext.getCmp('V_INV_NO').getValue()) {
    		var params = 'reportParams=pdfsavename:' + Ext.getCmp('V_TITLE').getValue() + '&INV_NO=' + Ext.getCmp('V_INV_NO').getValue();
    		url = url + params;
    		
    		Ext.Msg.confirm('확인', button.getText() + ' 출력하시겠습니까?', function(btn) {
        		if (btn == 'yes') {
					var myWin = new Ext.Window({
						title : button.getText(),
						html : '<iframe name="xxx" border =0 src="'+url+'" width="100%" height="100%"></iframe>',
						width : 1000,
						height : 768,
						modal : true
					});
					
					myWin.show();
					myWin.setSize(Ext.getBody().getViewSize());
					myWin.setPagePosition(0, 0);
        		}
        	})
    	} else {
    		Ext.Msg.alert('확인', '인보이스가 존재하지 않습니다.');
    	}
    },
    
    setTitle: function() {
    	var store1 = Ext.getStore('MyStore1');
    	var title = '';
    	
    	var etd = Ext.getCmp('V_ETD').getValue();
		title += etd.getFullYear()+'-'+(etd.getMonth()+1).toString().padStart(2,'0')+'-'+etd.getDate().toString().padStart(2,'0');
		
		if(Ext.getCmp('V_TRANS_TYPE').getValue() == 'AIR'){
			title += '_Air_docs_';
		} else {
			title += '_Ship_docs_';
		}
		title += Ext.getCmp('V_BP_NM').getValue();
		
		if(store1.data.length > 0){
			if(store1.data.items[0].get('MAKER')){
				title += '_' + store1.data.items[0].get('MAKER');
				if(store1.data.length > 1){
					title += ' 외';
				}
			}
			
			if(store1.data.items[0].get('ITEM_NM')){
				title += '_' + store1.data.items[0].get('ITEM_NM');
				if(store1.data.length > 1){
					title += ' 외';
				}
			}
		}
		
		var date = new Date();
		title += '(' + (date.getMonth()+1) + '.' + date.getDate() + '작업)';
		
		Ext.getCmp('V_TITLE').setValue(title);
    },
    
    onLaunch: function(application) {
    	var BPstore = Ext.getStore('WinBpPopStore');
        BPstore.load();
        
        var TradeInfoStore = Ext.getStore('TradeInfoStore');
        TradeInfoStore.load();
        
        var ItemStore = Ext.getStore('ItemStore');
        ItemStore.load();
    },
    
});
