/*
 * File: app/controller/MyGridController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_OFFER_CFM.controller.MyGridController', {
    extend: 'Ext.app.Controller',
    stores: ['MyStore', 'MyStore1'],
    control: {
		"#myGrid" : {
			cellclick : 'cellClick'
		}
    },

    cellClick : function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
    	var MAST_PO_NO = record.get('MAST_PO_NO');
    	
    	var store1 = Ext.getStore('MyStore1');
    	store1.load({
    		params: {
				V_TYPE: 'SD',
    			V_COMP_ID: parent.Ext.getCmp('GCOMP_ID').getValue(),
    			V_USR_ID: parent.Ext.getCmp('GUSER_ID').getValue(),
				V_MAST_PO_NO: MAST_PO_NO,
			},
    		callback: function(records,operations,success){
    			var OF_CFM_YN = store1.getAt(0).data.OF_CFM_YN;
    			
    			if(OF_CFM_YN == 'Y' && "/ADMIN/HDH_HSPF/LHR4558/JASONPARK/JWLEE/SMDSM1".indexOf(parent.Ext.getCmp('GUSER_ID').getValue()) < 0) {
		    		Ext.getCmp('gridSaveBtn').setDisabled(true);
		    	} else {
		    		Ext.getCmp('gridSaveBtn').setDisabled(false);
		    	}
    		}
    	});
    },
    
    gridSaveBtnClick: function(button, e, eOpts) {
    	var store1 = Ext.getStore('MyStore1');
    	var gridRecord = Ext.getCmp('myGrid1').getSelectionModel().getSelection();
    		
    	store1.sync({
			params: {
				V_TYPE : 'SYNC',
				V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
				V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
				V_MAST_PO_NO: Ext.getCmp('V_MAST_PO_NO').getValue(),
			},
			callback: function(records, operation, success) {
				store1.reload();
			}
		});
    },


});
