/*
 * File: app/view/MyGrid1.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_IV_DISTR.view.MyGrid1', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mygrid1',

    requires: [
        'M_IV_DISTR.view.MyGrid1ViewModel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.Exporter',
        'Ext.grid.plugin.CellEditing'
    ],

    viewModel: {
        type: 'mygridpanel11'
    },
    style: 'border: 1px solid lightgray; padding: 5px;',
    bodyBorder: false,
    header: false,
    title: 'My Grid Panel',
    id: 'myGrid1',
    store: 'MyStore1',
    config: {
        tbar: [
				{
				    id: 'gridAddBtn',
				    text: '',
				    margin: '0 3 0 0',
				    glyph: 'xf055@FontAwesome',
				    iconCls: 'grid-add-btn',
				    disabled: true
				},
				{
				    id: 'gridDelBtn',
				    text: '',
				    margin: '0 3 0 0',
				    glyph: 'xf056@FontAwesome',
				    iconCls: 'grid-del-btn',
				//    disabled: true
				},
				{
					   xtype: 'button',
					   id: 'ivRegBtn',
					   text: '매입등록',
				    	style: 'background-color: white; border: 0.5px solid #3367d6;',
				    	cls: 'blue-btn',
				},
               {
                   xtype: 'container',
                   flex: 1
               },
               {
             	   xtype: 'button',
             	   id: 'tempGlCfmBtn',
             	   margin: '0 3 0 0',
             	   text: 'ERP전표생성',
             	   style: 'background-color: white; border: 0.5px solid #3367d6;',
             	   cls: 'blue-btn',
             	   listeners: {
             		   mouseover: function(button, e, eOpts) {
             		        var theTip = Ext.create('Ext.tip.ToolTip', {
             		            html: 'ERP 결의전표 생성',
             		            target: 'tempGlCfmBtn',
             		            showDelay: 0,
             		            mouseOffset:[5,5],
             		            trackMouse: true,
             		            shadow: false
             		        });
             		    }
             	   },
             	   disabled: true
                },
                {
             	   xtype: 'button',
             	   id: 'tempGlCancelBtn',
             	   margin: '0 3 0 0',
             	   text: 'ERP전표취소',
             	   style: 'background-color: white; border: 0.5px solid #3367d6;',
             	   cls: 'blue-btn',
             	   listeners: {
             		   mouseover: function(button, e, eOpts) {
             		        var theTip = Ext.create('Ext.tip.ToolTip', {
             		            html: 'ERP 결의전표 삭제',
             		            target: 'tempGlCancelBtn',
             		            showDelay: 0,
             		            mouseOffset:[5,5],
             		            trackMouse: true,
             		            shadow: false
             		        });
             		    }
             	   },
             	   disabled: true
                },
               {
                   xtype: 'button',
                   glyph: 'xf1c3@FontAwesome',
                   id: 'xlsxDown1',
                   cfg: {
                       type: 'excel07',
                       ext: 'xlsx'
                   },
                   iconCls: 'grid-excel-btn',
               }
           ]
    },

    columns: [
        {
            xtype: 'rownumberer',
            width: 40
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 114,
            dataIndex: 'ITEM_CD',
            text: '품목코드'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 150,
            dataIndex: 'ITEM_NM',
            text: '품목명'
        },
        {
        	xtype: 'gridcolumn',
        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
        	width: 150,
        	dataIndex: 'BL_DOC_NO',
        	text: 'B/L번호'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 114,
            dataIndex: 'string',
            text: '규격'
        },
        {
            xtype: 'numbercolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            align: 'end',
            dataIndex: 'BOX_QTY',
            text: 'BOX수량',
            format: '0,000'
        },
        {
            xtype: 'numbercolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            align: 'end',
            dataIndex: 'BOX_WGT_UNIT',
            text: '단위중량'
        },
        {
            xtype: 'numbercolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            align: 'end',
            dataIndex: 'IV_QTY',
            text: '총중량',
            format: '0,000.00'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 100,
            dataIndex: 'CUR',
            text: '화폐단위',
            align: 'center',
            hidden: true
        },
        {
        	xtype: 'numbercolumn',
        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
        	align: 'end',
        	dataIndex: 'IV_PRC',
        	text:'매입단가',
        	format: '0,000.00'
        },
        {
        	xtype: 'numbercolumn',
        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
        	align: 'end',
        	dataIndex: 'IV_AMT',
        	text: '외화금액',
        	format: '0,000.00',
        	width: 120,
        	hidden: true
        },
        {
            xtype: 'numbercolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            align: 'end',
            dataIndex: 'IV_LOC_AMT',
            text: '자국금액',
            format: '0,000',
        	width: 120
        },
        {
        	xtype: 'numbercolumn',
        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
        	align: 'end',
        	dataIndex: 'IV_LOC_AMT',
        	text: '선물환율자국금액',
        	format: '0,000',
        	width: 130
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 150,
            dataIndex: 'MVMT_NO',
            hidden: true
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 150,
            dataIndex: 'VAT_TYPE_NM',
            text: '부가세유형'
        },
        {
        	xtype: 'numbercolumn',
        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
        	width: 110,
        	dataIndex: 'VAT_AMT',
            text: '부가세금액',
            format: '0,000',
            align: 'end'
        },
        {

            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 150,
            dataIndex: 'DATA',
            text: '유통이력번호'
        
        }
        
    ],
    selModel: {
        selType: 'checkboxmodel',
        listeners: {
        	select: function(rowmodel, record, index, eOpts) {
        		record.set('V_TYPE', 'V');
        	},
        	deselect: function(rowmodel, record, index, eOpts) {
        		record.set('V_TYPE', '');
        	}
        }
    },
    plugins: [
        {
            ptype: 'gridexporter'
        },
        {
            ptype: 'cellediting'
        }
    ]

});