/*
 * File: app/view/WinAddRow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_FORWARD_EXCHANGE_REQ_HSPF.view.WinAddRow', {
    extend: 'Ext.window.Window',
    alias: 'widget.winaddrow',

    requires: [
        'M_FORWARD_EXCHANGE_REQ_HSPF.view.WinAddRowViewModel',
        'Ext.container.Container',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'winaddrow'
    },
    modal: true,
    resizable: false,
    height: 700,
    width: 1400,
    title: 'B/L 리스트',
    id: 'popWindow',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            margin: '3 0 0 0',
            items: [
                {
                    xtype: 'button',
                    id : 'W_SelectBtn',
                    text: '조회'
                }
            ]
        },
        {
            xtype: 'container',
            margin: '3 0 0 0',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                	xtype: 'textfield',
                	id: 'W_LC_DOC_NO',
                	labelStyle: 'text-align: center',
                	fieldLabel: '신용장번호',
                	cls: 'pop_search',
                },
                {
                	xtype: 'textfield',
                	id: 'W_BL_DOC_NO',
                	labelStyle: 'text-align: center',
                	fieldLabel: 'B/L번호',
                	cls: 'pop_search',
                },
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            margin: '3 0 0 0',
            layout: 'fit',
            items: [
                {
                    xtype: 'gridpanel',
                    header: false,
                    title: 'My Grid Panel', 
                    store: 'PopStore',
                    id: 'popGrid',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            style: ' text-align: center; font-weight: bold;',
                            dataIndex: 'LC_DOC_NO',
                            text: '신용장번호',
                            width: 180,
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'LC_NO',
                        	text: '신용장번호',
                        	hidden: true,
                        },
                        {
                            xtype: 'gridcolumn',
                            style: ' text-align: center; font-weight: bold;',
                            dataIndex: 'BL_DOC_NO',
                            text: 'B/L번호',
                            width: 180,
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'BL_NO',
                        	text: 'B/L번호',
                        	hidden: true
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'DEPT_NM',
                        	text: '부서',
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'DEPT_CD',
                        	text: '부서',
                        	hidden: true
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'S_BP_NM',
                        	text: '매출처',
                        	width: 250,
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'S_BP_CD',
                        	text: '매출처',
                        	hidden: true
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'SALE_TYPE_NM',
                        	text: '판매구분',
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'SALE_TYPE_CD',
                        	text: '판매구분',
                        	hidden: true
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: ' text-align: center; font-weight: bold;',
                        	dataIndex: 'CUR',
                        	text: '통화',
                        },
                        {
                        	xtype: 'numbercolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
                        	align: 'end',
                        	dataIndex: 'DOC_AMT',
                        	text: '인수금액',
                        },
                        
                        
                    ],
                    viewConfig: {
                    	enableTextSelection: true,
                    },
                }
            ]
        }
    ]

});