/*
 * File: app/view/MyGrid.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('B_BIZ_DISTR.view.MyGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.myGrid',

    requires: [
        'B_BIZ_DISTR.view.MyGridViewModel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.Exporter',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.plugin.Clipboard',
    ],

    config: {
        tbar: [
            {
                id: 'gridAddBtn',
                text: '',
                margin: '0 3 0 0',
                glyph: 'xf055@FontAwesome',
                iconCls: 'grid-add-btn',
                disabled: true
            },
            {
                id: 'gridDelBtn',
                text: '',
                margin: '0 3 0 0',
                glyph: 'xf056@FontAwesome',
                iconCls: 'grid-del-btn',
                disabled: true
            },
            {
                xtype: 'container',
                flex: 1
            },
            {
                xtype: 'button',
                glyph: 'xf1c3@FontAwesome',
                id: 'xlsxDown',
                cfg: {
                    type: 'excel07',
                    ext: 'xlsx'
                },
                iconCls: 'grid-excel-btn',
                margin: '0 3 0 0',
                
            }
        ]
    },

    viewModel: {
        type: 'mygrid'
    },
    style: 'border: 1px solid lightgray; padding: 5px;',
    header: false,
    title: 'My Grid Panel',
    store: 'MyStore',
    id: 'myGrid',
    columns: [
        {
            xtype: 'rownumberer',
            width: 40
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 114,
            dataIndex: 'V_TYPE',
            text: 'V_TYPE',
            hidden: true
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 100,
            dataIndex: 'BP_CD',
            align: 'center',
            text: '거래처코드'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 200,
            dataIndex: 'BP_NM',
            text: '거래처명'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 114,
            dataIndex: 'BIZ_TYPE_NM',
            text: '거래처구분'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 130,
            dataIndex: 'BP_REGNO',
            text: '사업자번호'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 114,
            dataIndex: 'REG_NM',
            text: '대표자명'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 114,
            dataIndex: 'IND_TYPE',
            text: '업종',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 200,
            dataIndex: 'IND_CLASS',
            text: '업태',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 350,
            dataIndex: 'ADDRESS',
            text: '주소',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 120,
            dataIndex: 'TEL_NO',
            text: '전화번호',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 120,
            dataIndex: 'FAX_NO',
            text: '팩스번호',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 200,
            dataIndex: 'REMARK',
            text: '비고',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 114,
            dataIndex: 'NATION',
            text: '국가',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 110,
            dataIndex: 'REGION',
            text: '소재지',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 114,
            dataIndex: 'MAIN_ITEM',
            text: '주제품',
            editor: {
            	xtype: 'textfield'
            }
        },
        {
            xtype: 'datecolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
            width: 100,
            dataIndex: 'CR_DT',
            format: 'Y-m-d',
            text: '설립일자',
            editor: {
            	xtype: 'datefield',
            	format: 'Y-m-d'
            }
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; ',
            width: 114,
            dataIndex: 'EVALUATION',
            text: '기업평가',
        },
        {
            xtype: 'datecolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; ',
            width: 100,
            dataIndex: 'VALID_DT',
            format: 'Y-m-d',
            text: '평가기준일',
        },
        {
        	xtype: 'gridcolumn',
        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
        	align: 'end',
        	dataIndex: 'BILL_AMT',
        	text: '매출액',
//        	format: '0,000.00',
        	width: 100,
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            align: 'end',
            dataIndex: 'CAPITAL_AMT',
            text: '자기자본',
//            format: '0,000.00',
        	width: 100,
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 100,
            dataIndex: 'BASE_YEAR',
            text: '기준년도',
            align: 'center'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold; ',
            width: 114,
            dataIndex: 'DEPT_CD',
            text: '영업팀',
            editor: {
            	xtype: 'textfield'
            },
        	filter: { 			//필터
        		type : 'list',
//                operator : 'in',
            },
        },
        {
        	xtype: 'datecolumn',
        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
        	width: 114,
        	format: 'Y-m-d',
        	dataIndex: 'UPDT_DT',
        	text: '최종수정일',
        }
    ],
    viewConfig: {
    	enableTextSelection: true,
    },
    selModel: {
        selType: 'checkboxmodel',
        checkOnly: true,
      listeners: {
      	select: function(rowmodel, record, index, eOpts) {
          	record.set('V_TYPE', 'V');
          },
          deselect: function(rowmodel, record, index, eOpts) {
          	record.set('V_TYPE', '');
          }
      }
  },
    plugins: [
        {
            ptype: 'gridexporter'
        },
        {
            ptype: 'cellediting',
            listeners: {
            	edit: function(editor, context, eOpts) {
            		var selModel = Ext.getCmp('myGrid').getSelectionModel();
            		selModel.select(context.record, true);
            	}
            }
        },
        {
            ptype: 'clipboard'
        },
        {
    		ptype: 'gridfilters' ///이부분
        },
    ]

});