/*
 * File: app/controller/MyGrid1Controller.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_GR_HSPF.controller.MyGridController1', {
    extend: 'Ext.app.Controller',

    stores: [
        'MyStore1'
    ],

    control: {
        "#grid1AddBtn": {
            click: 'grid1AddBtnClick'
        },
        "#grid1DelBtn": {
            click: 'grid1DelBtnClick'
        },
        "#xlsxDown1": {
            click: 'xlsxDown1Click'
        },
        "#xmlDown1": {
            click: 'xmlDown1Click'
        },
        "#grid1ApplyBtn": {
            click: 'grid1ApplyBtnClick'
        }
    },

    grid1AddBtnClick: function(button, e, eOpts) {
        var popup = Ext.create("M_GR_HSPF.view.WinAddRow1");
        popup.show();
        Ext.getCmp('rowCount1').setValue(1);
    },

    grid1DelBtnClick: function(button, e, eOpts) {
        var store = Ext.getStore('MyStore1');
            	var gridRecord = Ext.getCmp('myGrid1').getSelectionModel().getSelection();

            	if(gridRecord.length > 0) {
            		Ext.Msg.confirm('확인','삭제하시겠습니까?', function(button){
            			if(button == 'yes') {
            				store.remove(gridRecord);
//            				for(var i=0; i<gridRecord.length; i++) {
//            		    		if(gridRecord[i].data['V_TYPE']=='V') {
//            		    			gridRecord[i].data['V_TYPE'] = 'D';
//            		    		}
//            		    	}
//            		    	store.sync({
//            					params: {
//            						V_USR_ID : 'admin',//parent.Ext.getCmp('GUSER_ID').getValue(),
//            					},
//            		    		callback: function(records, operation, success) {
//            		    			store.reload();
//            					}
//            		    	});
            			}
            		});
            	}
    },

    xlsxDown1Click: function(button, e, eOpts) {
        var currentDate = Ext.util.Format.date(new Date(), 'Y-m-d His');
            	var grid = Ext.getCmp('myGrid1');
            	grid.saveDocumentAs({
                    type: 'xlsx',
                    title: 'test', //엑셀내타이틀
                    fileName: currentDate+'.xlsx' //엑셀파일이름
        		});
    },

    xmlDown1Click: function(button, e, eOpts) {
        var currentDate = Ext.util.Format.date(new Date(), 'Y-m-d His');
            	var grid = Ext.getCmp('myGrid1');
            	grid.saveDocumentAs({
                    type: 'xml',
                    title: 'test', //엑셀내타이틀
                    fileName: currentDate+'.xml' //엑셀파일이름
        		});
    },

    grid1ApplyBtnClick: function(button, e, eOpts) {
        alert('적용');
    }

});
