/*
 * File: app/store/PurChaeCfmYnStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rawpurching.store.PurChaeCfmYnStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Rawpurching.model.RawPurHeadSave',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'PurChaeCfmYnStore',
            model: 'Rawpurching.model.RawPurHeadSave',
            proxy: {
                type: 'ajax',
                url: '/swm/custom/rawpurchase/HsnCustomPurHeadInsert.do',
                reader: {
                    type: 'json',
                    rootProperty: 'resultList'
                }
            }
        }, cfg)]);
    }
});