/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('S_COG_INSP_STS_TOT_HSPF.model.MyModel', {
	extend : 'Ext.data.Model',

	requires : [ 'Ext.data.field.Field' ],
	fields : [ 
		{
			name : 'MVMT_BL_QTY',
			type : 'float'
		}, {
			name : 'MVMT_SOJE_QTY',
			type : 'float'
		}, {
			name : 'MVMT_PRC',
			type : 'float'
		}, {
			name : 'MAGIN_WIDTH',
			type : 'float'
		}, {
			name : 'DN_QTY',
			type : 'float'
		}, {
			name : 'SALES_PRC',
			type : 'float'
		}, {
			name : 'PURCHASE_PRC',
			type : 'float'
		}, {
			name : 'SOJE_PUR_PRC',
			type : 'float'
		}, {
			name : 'DOC_PRC',
			type : 'float'
		}, {
			name : 'XCHG_RATE1',
			type : 'float'
		}, {
			name : 'MVMT_LOC_AMT',
			type : 'float'
		}, {
			name : 'MVMT_SOJE_AMT',
			type : 'float'
		}, {
			name : 'INDIVIDUAL_SALES_PRC',
			type : 'float'
		}, {
			name : 'CC_LOC_AMT',
			type : 'float'
		}, {
			name : 'DISTRIBT_AMT',
			type : 'float'
		}, {
			name : 'DISTRIBT_PRC',
			type : 'float'
		}, {
			name : 'TOT_DISTRIBT_AMT',
			type : 'float'
		}, {
			name : 'TOT_IV_AMT',
			type : 'float'
		}, {
			name : 'SOJE_SALE_PRC',
			type : 'float'
		}, {
			name : 'INDIVIDUAL_SALES_AMT',
			type : 'float'
		}, {
			name : 'PROFIT',
			type : 'float'
		}, {
			name : 'MVMT_UNIT2',
			type : 'float'
		}, {
			name : 'INDIVIDUAL_SALES_PRC2',
			type : 'float'
		}, {
			name : 'AVG_PRC',
			type : 'float'
		}, {
			name : 'INDIVIDUAL_SALES_PRC2_SUM',
			type : 'float'
		}, {
			name : 'AVG_AMT',
			type : 'float'
		}, {
			name : 'AVG_PRC2',
			type : 'float'
		}, {
			name : 'AVG_AMT2',
			type : 'float'
		}, 
	],
});