/*
 * File: app/store/CodeStore.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LOGIS_BILL.store.CodeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'LOGIS_BILL.model.CodeModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CodeStore',
            autoLoad: false,
            model: 'LOGIS_BILL.model.CodeModel',
            proxy: {
                type: 'ajax',
                api: {
                    read: 'sql/logis_bill_code.jsp',
                    //create: 'sql/logis_bill.jsp',
                    //destroy: 'sql/logis_bill.jsp',
                    //update: 'sql/logis_bill.jsp'
                },
                extraParams: {
                    V_TYPE: 'S'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'resultList'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    encode: true,
                    rootProperty: 'data'
                },
                listeners: {
                    exception: {
                        fn: me.onAjaxException,
                        scope: me
                    }
                }
            }
        }, cfg)]);
    },

    onAjaxException: function(proxy, response, operation, eOpts) {
        Ext.Msg.alert('결과', response.responseText);
    }

});