/*
 * File: app/controller/WinAddRow1BtnController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('S_CONT_HSPF.controller.WinAddRow1BtnController', {
    extend: 'Ext.app.Controller',

    control: {
        "#WinPopSelBtn": {
            click: 'WinPopSelBtnClick'
        }
    },

    WinPopSelBtnClick: function(button, e, eOpts) {
        alert('select');
        //    	var store = this.getMyStoreStore();
        //    	store.removeAll();
        //    	store.load({
        //    		params: {
        //    			V_TYPE: 'S',
        //    			V_COMP_ID: Ext.getCmp('V_COMP_ID').getValue(),
        //    			V_COMP_NM: Ext.getCmp('V_COMP_NM').getValue()
        //    		},
        //    		callback: function(records,operations,success){
        //    		}
        //    	})
    }

});
