/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SCM_DLVY_HSPF.model.MyModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'PO_NO'
        },
        {
            name: 'PO_SEQ'
        },
        {
            name: 'ITEM_CD'
        },
        {
            name: 'ITEM_NM'
        },
        {
            name: 'SPEC'
        },
        {
            name: 'UNIT'
        },
        {
            name: 'PO_DT'
        },
        {
            name: 'DLVY_HOPE'
        },
        {
            name: 'PO_QTY'
        },
        {
            name: 'IN_QTY'
        },
        {
            name: 'ASN_NO_QTY'
        },
        {
            name: 'DLVY_AVL_QTY'
        },
        {
            name: 'DLVY_AVL_DT',
            format: 'date'
        },
        {
            name: 'SL_CD'
        },
        {
            name: 'BAR_CD_CNT'
        }
    ]
});