/*
 * File: app/view/MySearchForm.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('S_DN_SELECT_HSPF.view.MySearchForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.mysearchform',

    requires: [
        'S_DN_SELECT_HSPF.view.MySearchFormViewModel',
        'Ext.form.FieldSet',
        'Ext.form.FieldContainer',
        'Ext.form.field.Date'
    ],

    viewModel: {
        type: 'mysearchform'
    },
    padding: '',
    layout: 'auto',
    bodyPadding: 10,
    header: false,
    title: 'MyForm',

    items: [
        {
            xtype: 'fieldset',
            cls: 'gridfieldset',
            height: 150,
            maxHeight: 150,
            minHeight: 150,
            title: 'Search',
            layout: {
                type: 'vbox',
                align: 'stretch',
                pack: 'center',
                padding: 10
            },
            items: [
                {
                    xtype: 'fieldcontainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                    	{
            	        	xtype: 'textfield',
            	        	id: 'V_S_BP_NM',
            	        	maxWidth: 250,
            	        	minWidth: 250,
            	        	width: 250,
            	        	fieldLabel: '출고처',
            	        	labelWidth: 80,
            	        	name: 'search_field',
            	        	emptyText: 'Double Click',
                            listeners: {
                                afterrender: function(c) {
                                	c.getEl().on('dblclick', function() {
                                		var popup = Ext.create("Popup.view.WinSBpPop");
                                        popup.show();
                                        
                                        Ext.getCmp('fieldType').setValue('textfield');
                                        var store = Ext.getStore('WinSBpPopStore');
                                		store.removeAll();
                                    });
                                }
                            },
            	        },
            	        {
            	        	xtype: 'textfield',
            	        	id: 'V_S_BP_CD',
            	        	maxWidth: 250,
            	        	minWidth: 250,
            	        	width: 250,
            	        	fieldLabel: '출고처',
            	        	labelWidth: 80,
            	        	name: 'search_field',
                            hidden: true
            	        },
                        {
                            xtype: 'datefield',
                            id: 'V_DN_DT_FR',
                            margin: '0 0 0 100',
                            maxWidth: 250,
                            minWidth: 250,
                            width: 250,
                            fieldLabel: '출고일',
                            labelWidth: 80,
                            name: 'search_field',
                            format: 'Y-m-d',
                            listeners : {
                                render : function(datefield) {
                                	var nows = new Date();
                                	nows.setDate(1);
                                    datefield.setValue(nows);
                                }	
                            },
                        },
                        {
                            xtype: 'datefield',
                            id: 'V_DN_DT_TO',
                            margin: '0 0 0 3',
                            maxWidth: 170,
                            minWidth: 170,
                            width: 170,
                            fieldLabel: '~',
                            labelWidth: 10,
                            name: 'search_field',
                            format: 'Y-m-d',
                            listeners : {
                                render : function(datefield) {
                                	var nows = new Date();
                                    datefield.setValue(nows);
                                }	
                            },
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    margins: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'V_ITEM_CD',
                            maxWidth: 250,
                            minWidth: 250,
                            width: 250,
                            fieldLabel: '품목코드',
                            labelWidth: 80,
                            name: 'search_field',
                        },
                        {
                            xtype: 'textfield',
                            id: 'V_ITEM_NM',
                            margin: '0 0 0 100',
                            maxWidth: 250,
                            minWidth: 250,
                            width: 250,
                            fieldLabel: '품목명',
                            labelWidth: 80,
                            name: 'search_field',
                        },
                        {
                            xtype: 'textfield',
                            id: 'V_BL_NO',
                            margin: '0 0 0 100',
                            maxWidth: 250,
                            minWidth: 250,
                            width: 250,
                            fieldLabel: 'BL번호',
                            labelWidth: 80,
                            name: 'search_field',
                        }
                    ]
                }
            ]
        }
    ]

});