/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_IMP_CHK_TOT_HSPF.model.MyModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'FR_I_BP_QTY',
            type: 'float',
        },
        {
            name: 'FR_O_BP_QTY',
            type: 'float',
        },
        {
            name: 'FR_MB_BP_QTY',
            type: 'float',
        },
        {
            name: 'FR_MT_BP_QTY',
            type: 'float',
        },
        {
            name: 'FR_M_QTY',
            type: 'float',
        },
        {
            name: 'FR_D_QTY',
            type: 'float',
        },
        {
            name: 'ST_MT_QTY',
            type: 'float',
        },
        {
            name: 'ST_INMT_QTY',
            type: 'float',
        },
        {
            name: 'ST_TP_QTY',
            type: 'float',
        },
        {
            name: 'ST_NET_QTY',
            type: 'float',
        },
        {
            name: 'ST_KY_QTY',
            type: 'float',
        },
        {
            name: 'ST_KY_DIFF_QTY',
            type: 'float',
        },
        {
            name: 'ST_CY_QTY',
            type: 'float',
        },
        {
            name: 'ST_TOT_QTY',
            type: 'float',
        },
        {
            name: 'AVL_MT_USE_QTY',
            type: 'float',
        },
        {
            name: 'FR_ADD_QTY',
            type: 'float',
        },
        {
            name: 'HSTN_QTY',
            type: 'float',
        },
        {
            name: 'HSMI_QTY',
            type: 'float',
        },
        
        {
            name: 'SF_DAY',
            type: 'float',
        },
        {
            name: 'AVL_DAY',
            type: 'float',
        },
        {
            name: 'AVL_MT_USE_QTY',
            type: 'float',
        },
        {
            name: 'AVL_MT_USE_RT',
            type: 'float',
        },
        {
            name: 'AVL_I_USE_QTY',
            type: 'float',
        },
        {
            name: 'AVL_O_USE_QTY',
            type: 'float',
        },
        {
            name: 'AVL_TOT_USE_QTY',
            type: 'float',
        },
        {
            name: 'AVL_TOT_USE_RT',
            type: 'float',
        },
        {
            name: 'AVL_DAY_USE_RT',
            type: 'float',
        },
        {
            name: 'LT_MNTH',
            type: 'float',
        },
        {
            name: 'LT_DAY',
            type: 'float',
        },
        {
            name: 'MIN_PO_QTY',
            type: 'float',
        },
        
        {
            name: 'FR_QTY',
            type: 'float',
            allowNull: true
        },
        {
            name: 'PLAN_D_QTY',
            type: 'float',
            allowNull: true
        },
        {
            name: 'FR_NEXT1_QTY',
            type: 'float',
            allowNull: true
        },
        {
            name: 'FR_NEXT2_QTY',
            type: 'float',
            allowNull: true
        },
        {
            name: 'FR_NEXT3_QTY',
            type: 'float',
            allowNull: true
        },
        {
            name: 'FR_NEXT4_QTY',
            type: 'float',
            allowNull: true
        },
        {
            name: 'FR_NEXT5_QTY',
            type: 'float',
            allowNull: true
        },
        {
            name: 'BEFORE1_QTY',
            type: 'float',
        },
        {
            name: 'BEFORE2_QTY',
            type: 'float',
        },
        {
            name: 'BEFORE3_QTY',
            type: 'float',
        },
        {
            name: 'BEFORE4_QTY',
            type: 'float',
        },
        {
            name: 'BEFORE5_QTY',
            type: 'float',
        },
        
        {
            name: 'PO_QTY1',
            type: 'float',
        },
        {
            name: 'PO_QTY2',
            type: 'float',
        },
        {
            name: 'PO_QTY3',
            type: 'float',
        },
        {
            name: 'PO_QTY4',
            type: 'float',
        },
        {
            name: 'PO_QTY5',
            type: 'float',
        },
        {
            name: 'PO_QTY6',
            type: 'float',
        },
        {
            name: 'PO_QTY7',
            type: 'float',
        },
        {
            name: 'PO_QTY8',
            type: 'float',
        },
        {
            name: 'PO_QTY9',
            type: 'float',
        },
        {
            name: 'PO_QTY10',
            type: 'float',
        },
        {
            name: 'PO_QTY11',
            type: 'float',
        },
        {
            name: 'PO_QTY12',
            type: 'float',
        },
        {
            name: 'PO_QTY13',
            type: 'float',
        },
        {
            name: 'PO_QTY14',
            type: 'float',
        },
        {
            name: 'PO_QTY15',
            type: 'float',
        },
        {
            name: 'PO_QTY16',
            type: 'float',
        },
        {
            name: 'PO_QTY17',
            type: 'float',
        },
        {
            name: 'PO_QTY18',
            type: 'float',
        },
        {
            name: 'PO_QTY19',
            type: 'float',
        },
        {
            name: 'PO_QTY20',
            type: 'float',
        },
    ]
});