/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Y_APPROV_DISTR.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'Y_APPROV_DISTR.view.MyPanelViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.FieldContainer',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.Exporter',
        'Ext.grid.plugin.CellEditing',
        'Ext.resizer.Splitter',
        'Ext.grid.plugin.Clipboard',
    ],

    viewModel: {
        type: 'mypanel'
    },
    itemId: 'mypanel',
    layout: 'fit',
    header: false,
    title: 'Tab 1',

    items: [
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    layout: 'auto',
                    bodyPadding: '0 10 0 10',
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                        	hidden: true,
                            xtype: 'fieldset',
                            height: 100,
                            maxHeight: 100,
                            minHeight: 100,
                            collapsible: true,
                            title: '[ Search ]',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
//                                        {
//                                            xtype: 'textfield',
//                                            maxWidth: 250,
//                                            minWidth: 250,
//                                            width: 250,
//                                            fieldLabel: '리스크관리번호',
//                                            name: 'search_field',
//                                            id: 'V_RISK_REF_NO',
//                                            emptyText: '(Double Click)',
//                                            listeners: {
//                                                afterrender: function(c) {
//                                                	c.getEl().on('dblclick', function() {
//                                                		var popup = Ext.create("Y_APPROV_DISTR.view.WinRiskPop");
//                                                        
//                                                        popup.setSize(Ext.getBody().getViewSize());
//                                                        popup.show();
//                                                        
//                                                        var store = Ext.getStore('PopStore');
//                                                		store.removeAll();
//                                                    });
//                                                }
//                                            }
//                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 230,
                                            minWidth: 230,
                                            width: 230,
                                            fieldLabel: '품의번호',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            hidden: true,
                                            id: 'S_APPROV_NO'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 230,
                                            minWidth: 230,
                                            width: 230,
                                            fieldLabel: '품의명',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            hidden: true,
                                            id: 'S_APPROV_NM'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 230,
                                            minWidth: 230,
                                            width: 230,
                                            fieldLabel: '차수',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'S_APPROV_SEQ',
                                            hidden: true
                                            	
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 180,
                            maxHeight: 180,
                            minHeight: 180,
                            collapsible: true,
                            title: '[ 품의등록정보 ]',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                    {
                                    	xtype: 'fieldcontainer',
                                    	layout: {
                                    		type: 'hbox',
                                    		align: 'stretch'
                                    	},
                                    	items: [
											{
											    xtype: 'textfield',
											    maxWidth: 250,
											    minWidth: 250,
											    width: 250,
											    fieldLabel: '리스크관리번호',
											    name: 'search_field',
											    id: 'V_RISK_REF_NO',
											    emptyText: '(Double Click)',
											    listeners: {
											        afterrender: function(c) {
											        	
											        	c.getEl().on('dblclick', function() {
											        		var popup = Ext.create("Y_APPROV_DISTR.view.WinRiskPop");
											                
											                popup.setSize(Ext.getBody().getViewSize());
											                popup.show();
											                
											                var store = Ext.getStore('PopStore');
											                Y_APPROV_DISTR.app.getController("RiskPopController").w_riskSelBtnClick();
											                
//											        		store.removeAll();
											            });
											        }
											    }
											},
											{
												xtype: 'container',
												flex: 1,
											},
											{
												xtype: 'button',
												text: '영업당담자 비율',
												id: 'PLBtn',
												listeners:{
													click:function(c){
														if(Ext.getCmp('V_APPROV_MGM_NO').getValue() == '' || Ext.getCmp('V_APPROV_MGM_NO').getValue() == null || Ext.getCmp('V_APPROV_MGM_NO').getValue() == undefined){
															Ext.Msg.alert('확인', '품의 조회 후 눌러주세요');
														}
														else{
															var window = Ext.create('Y_APPROV_DISTR.view.PLWindow');
															var store = Ext.getCmp('PLGrid').getStore();
															store.load({
																params:{
																	V_COMP_ID : 'HSN',
																	V_TYPE : 'S',
																	V_APPROV_NO : Ext.getCmp('V_APPROV_MGM_NO').getValue()
																		
																}
															});
															Ext.getCmp('V_PL_APPROV_NO').setValue(Ext.getCmp('V_APPROV_MGM_NO').getValue());
															window.show();
														}
														
													}
												}
											}
										]
                                    },
                                {
                                    xtype: 'fieldcontainer',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            maxWidth: 250,
                                            minWidth: 250,
                                            width: 250,
                                            fieldLabel: '품의관리번호',
                                            name: 'search_field',
                                            id: 'V_APPROV_MGM_NO',
                                            emptyText: '(Double Click)',
                                            listeners: {
                                                afterrender: function(c) {
                                                	c.getEl().on('dblclick', function() {
                                                		var popup = Ext.create("Y_APPROV_DISTR.view.WinApprovPop");
                                                        
                                                        popup.setSize(Ext.getBody().getViewSize());
                                                        popup.show();
                                                        
//                                                        var store = Ext.getStore('PopStore1');
//                                                		store.removeAll();
                                                        Y_APPROV_DISTR.app.getController("ApprovPopController").w_approvSelBtnClick();
                                                    });
                                                }
                                            },
                                            fieldStyle: 'background-color: #ffefbb'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 230,
                                            minWidth: 230,
                                            width: 230,
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_S_BP_CD',
                                            hidden: true
                                        },
                                        {
                                        	xtype: 'textfield',
                                        	margin: '0 0 0 30',
                                        	maxWidth: 230,
                                        	minWidth: 230,
                                        	width: 230,
                                            fieldLabel: '<span style=\'color:red\'>*</span>수주처',
                                        	labelWidth: 80,
                                        	name: 'search_field',
                                        	id: 'V_S_BP_NM',
                                            emptyText: '(Double Click)',
                                            listeners: {
                                                afterrender: function(c) {
                                                	c.getEl().on('dblclick', function() {
                                            			var popup = Ext.create("Popup.view.WinSBpPop");
                                            			popup.show();
                                            			
                                            			Ext.getCmp('fieldType').setValue('Y_APPROV_DISTR');
                                            			var store = Ext.getStore('WinSBpPopStore');
                                            			store.removeAll();
                                                    });
                                                },
                                                change: function(field, newValue, oldValue, eOpts) {
                                                	if(newValue.length == 0) {
                                                		Ext.getCmp('V_S_BP_CD').setValue('');
                                                	}
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 230,
                                            minWidth: 230,
                                            width: 230,
                                            fieldLabel: '<span style=\'color:red\'>*</span>품의번호',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_APPROV_NO'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 230,
                                            minWidth: 230,
                                            width: 230,
                                            fieldLabel: '<span style=\'color:red\'>*</span>품의차수',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_APPROV_SEQ'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 400,
                                            minWidth: 400,
                                            width: 400,
                                            fieldLabel: '<span style=\'color:red\'>*</span>품의명',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_APPROV_NM',
//                                            editable: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            maxWidth: 250,
                                            minWidth: 250,
                                            width: 250,
                                            fieldLabel: '<span style=\'color:red\'>*</span>품의일자',
                                            name: 'search_field',
                                            id: 'V_APPROV_DT',
                                            format: 'Y-m-d',
                                            listeners : {
                                                render : function(datefield) {
                                                	var nows = new Date();
                                                    datefield.setValue(nows);
                                                }	
                                            },
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '0 0 0 30',
                                            maxWidth: 230,
                                            minWidth: 230,
                                            width: 230,
                                            fieldLabel: '<span style=\'color:red\'>*</span>사업부구분',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_COMP_TYPE',
                                            displayField: 'DTL_NM',
                            	        	valueField: 'DTL_CD',
                            	        	editable: false,
                            	        	value: 'B',
                            	        	store: Ext.create('Ext.data.Store',{
                            	        		autoLoad: true,
                            	        		storeId: 'store1',
                            	        		proxy: {
                            	        			type: 'ajax',
                            	        			extraParams: {
                            	        				V_MAST_CD: 'BA25',
                            	        				V_GRID: 'Y'
                            	        			},	
                            	        			api: {
                            	        				read: '/HSPF01/common/sql/Combobox.jsp'
                            	        			},
                            	        			reader: {
                            	        				type: 'json',
                            	        				rootProperty: 'resultList'
                            	        			}
                            	        		}
                            	        	})
                            	        	,
                                    		listConfig: {
                                                itemTpl: [
                                                    '<div>{DTL_NM} ({DTL_CD})</div>'
                                                ]
                                            },
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '0 0 0 30',
                                            maxWidth: 180,
                                            minWidth: 180,
                                            width: 180,
                                            fieldLabel: '<span style=\'color:red\'>*</span>지역',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_REGION',
                                            displayField: 'DTL_NM',
                            	        	valueField: 'DTL_CD',
                            	        	editable: false,
                            	        	value: 8,
                            	        	store: Ext.create('Ext.data.Store',{
                            	        		autoLoad: true,
                            	        		storeId: 'store2',
                            	        		proxy: {
                            	        			type: 'ajax',
                            	        			extraParams: {
                            	        				V_MAST_CD: 'BA26',
                            	        				V_GRID: 'Y'
                            	        			},	
                            	        			api: {
                            	        				read: '/HSPF01/common/sql/Combobox.jsp'
                            	        			},
                            	        			reader: {
                            	        				type: 'json',
                            	        				rootProperty: 'resultList'
                            	        			}
                            	        		}
                            	        	})
                            	        	,
                                    		listConfig: {
                                                itemTpl: [
                                                    '<div>{DTL_NM} ({DTL_CD})</div>'
                                                ]
                                            },
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '0 0 0 30',
                                            maxWidth: 180,
                                            minWidth: 180,
                                            width: 180,
                                            fieldLabel: '판매유형',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_SALE_TYPE',
                                            displayField: 'DTL_NM',
                            	        	valueField: 'DTL_CD',
                            	        	editable: false,
                            	        	store: Ext.create('Ext.data.Store',{
                            	        		autoLoad: true,
                            	        		storeId: 'store3',
                            	        		proxy: {
                            	        			type: 'ajax',
                            	        			extraParams: {
                            	        				V_MAST_CD: 'BA10',
                            	        				V_GRID: 'Y'
                            	        			},	
                            	        			api: {
                            	        				read: '/HSPF01/common/sql/Combobox.jsp'
                            	        			},
                            	        			reader: {
                            	        				type: 'json',
                            	        				rootProperty: 'resultList'
                            	        			}
                            	        		}
                            	        	})
                            	        	,
                                    		listConfig: {
                                                itemTpl: [
                                                    '<div>{DTL_NM} ({DTL_CD})</div>'
                                                ]
                                            },
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '0 0 0 30',
                                            maxWidth: 180,
                                            minWidth: 180,
                                            width: 180,
                                            fieldLabel: '구매유형',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_IV_TYPE',
                                            displayField: 'DTL_NM',
                            	        	valueField: 'DTL_CD',
                            	        	editable: false,
                            	        	store: Ext.create('Ext.data.Store',{
                            	        		autoLoad: true,
                            	        		storeId: 'store4',
                            	        		proxy: {
                            	        			type: 'ajax',
                            	        			extraParams: {
                            	        				V_MAST_CD: 'BA18',
                            	        				V_GRID: 'Y'
                            	        			},	
                            	        			api: {
                            	        				read: '/HSPF01/common/sql/Combobox.jsp'
                            	        			},
                            	        			reader: {
                            	        				type: 'json',
                            	        				rootProperty: 'resultList'
                            	        			}
                            	        		}
                            	        	})
                            	        	,
                                    		listConfig: {
                                                itemTpl: [
                                                    '<div>{DTL_NM} ({DTL_CD})</div>'
                                                ]
                                            },
                                            listeners: {
                                            	select : function(combo, record, eOpts) {
                                            		if(record.data.DTL_CD == 'L') { //내수
                                            			Ext.getCmp('myGrid').down('[dataIndex=USANCE_TYPE]').setVisible(false);
                                            			Ext.getCmp('myGrid').down('[dataIndex=USANCE_RT]').setVisible(false);
                                            			Ext.getCmp('myGrid').down('[dataIndex=CONT_QTY]').setVisible(false);
                                            			Ext.getCmp('myGrid').down('[dataIndex=CONT_REMARK]').setVisible(false);
                                            			Ext.getCmp('myGrid').down('[dataIndex=INSUR_RT]').setVisible(false);
                                            			Ext.getCmp('myGrid').down('[dataIndex=REC_RT]').setVisible(false);
                                            			Ext.getCmp('myGrid').down('[dataIndex=LC_RT]').setVisible(false);
                                            			Ext.getCmp('myGrid').down('[dataIndex=PAY_METH]').setVisible(false);
                                            			
                                            		} else {
                                            			Ext.getCmp('myGrid').down('[dataIndex=USANCE_TYPE]').setVisible(true);
                                            			Ext.getCmp('myGrid').down('[dataIndex=USANCE_RT]').setVisible(true);
                                            			Ext.getCmp('myGrid').down('[dataIndex=CONT_QTY]').setVisible(true);
                                            			Ext.getCmp('myGrid').down('[dataIndex=CONT_REMARK]').setVisible(true);
                                            			Ext.getCmp('myGrid').down('[dataIndex=INSUR_RT]').setVisible(true);
                                            			Ext.getCmp('myGrid').down('[dataIndex=REC_RT]').setVisible(true);
                                            			Ext.getCmp('myGrid').down('[dataIndex=LC_RT]').setVisible(true);
                                            			Ext.getCmp('myGrid').down('[dataIndex=PAY_METH]').setVisible(true);
                                            			
                                            		}
                                            	}
                                            },
                                        },
                                        {
                                            xtype: 'numberfield',
                                            margin: '0 0 0 30',
                                            maxWidth: 180,
                                            minWidth: 180,
                                            width: 180,
                                            fieldLabel: '컨테이너수량',
                                            labelWidth: 80,
                                            name: 'search_field',
                                            id: 'V_CONT_QTY'
                                        },
                                        {
                                        	xtype: 'numberfield',
                                        	margin: '0 0 0 30',
                                        	maxWidth: 180,
                                        	minWidth: 180,
                                        	width: 180,
                                        	fieldLabel: '이익률',
                                        	labelWidth: 80,
                                        	name: 'search_field',
                                        	id: 'V_PROFIT_RT'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    style: 'border: 1px solid lightgray; padding: 5px;',
                    header: false,
                    title: 'My Grid Panel',
                    id: 'myGrid',
                    store: 'MyStore',
                    
                        tbar: [
                               {
                                   id: 'gridAddBtn',
                                   text: '',
                                   margin: '0 3 0 0',
                                   glyph: 'xf055@FontAwesome',
                                   iconCls: 'grid-add-btn',
                               },
                               {
                                   id: 'gridDelBtn',
                                   text: '',
                                   margin: '0 3 0 0',
                                   glyph: 'xf056@FontAwesome',
                                   iconCls: 'grid-del-btn',
                               },
                               {
	                               	id: 'gridSaveBtn',
	                               	xtype: 'button',
	                               	glyph: 'xf0c7@FontAwesome',
	                               	iconCls: 'grid-save-btn',
	                               	margin: '0 3 0 0'
                               },
                               {
                            	   id: 'gridCopyBtn',
                            	   xtype: 'button',
                            	   glyph: 'xf0c5@FontAwesome',
                            	   iconCls: 'grid-copy-btn',
                            	   margin: '0 3 0 0'
                               },
                               {
                                   xtype: 'container',
                                   flex: 1
                               },
                               {
                                   xtype: 'button',
                                   glyph: 'xf1c3@FontAwesome',
                                   id: 'xlsxDown1',
                                   cfg: {
                                       type: 'excel07',
                                       ext: 'xlsx'
                                   },
                                   iconCls: 'grid-excel-btn',
                               }
                           ],
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 40
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'V_TYPE',
                            text: 'V_TYPE',
                            hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6' ,
                            width: 114,
                            dataIndex: 'M_BP_CD',
                            text: '<span style=\'color:red\'>*</span>매입처코드',
                    		editor : {
                    			xtype : 'textfield',
                    			allowBlank : false,
                    			emptyText : '(Double Click)',
//                    			editable : false,
                    			listeners : {
                    				afterrender : function(c) {
                    					c.getEl().on('dblclick', function() {
                    						var popup = Ext.create("Popup.view.WinMBpPop");
                    						popup.show();
                    						
                    						Ext.getCmp('fieldType').setValue('Y_APPROV_DISTR');
                    						var store = Ext.getStore('WinMBpPopStore');
                    						store.removeAll();
                    					});
                    				}
                    			}
                    		},
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 150,
                            dataIndex: 'M_BP_NM',
                            text: '매입처명'
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 114,
                            dataIndex: 'BF_TYPE',
                            text: '<span style=\'color:red\'>*</span>축종',
                        	editor: {
                        		xtype: 'combobox',
                        		displayField: 'DTL_NM',
                        		autoLoadOnValue: true,
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: Ext.create('Ext.data.Store',{
                        			autoLoad: true,
                        			storeId: 'storea',
                        			proxy: {
                        		           type: 'ajax',
                        		           extraParams: {
                        		            	V_MAST_CD: 'BA11',
                        		            	V_GRID: 'Y'
                        		           },	
                        		           api: {
                        		               read: '/HSPF01/common/sql/Combobox.jsp'
                        		           },
                        		           reader: {
                        		               type: 'json',
                        		               rootProperty: 'resultList'
                        		           }
                        		       }
                        		}),
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                },
                        	},
                        	
                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.data.StoreManager.lookup('storea').findRecord('DTL_CD',value) !==null)
                                {
                                    return Ext.data.StoreManager.lookup('storea').findRecord('DTL_CD',value).get('DTL_NM');
                                }
                                return value;
                            },
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 114,
                            dataIndex: 'ST_TYPE',
                            text: '<span style=\'color:red\'>*</span>상태',
                        	editor: {
                        		xtype: 'combobox',
                        		displayField: 'DTL_NM',
                        		autoLoadOnValue: true,
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: Ext.create('Ext.data.Store',{
                        			autoLoad: true,
                        			storeId: 'storeb',
                        			proxy: {
                        		           type: 'ajax',
                        		           extraParams: {
                        		            	V_MAST_CD: 'BA12',
                        		            	V_GRID: 'Y'
                        		           },	
                        		           api: {
                        		               read: '/HSPF01/common/sql/Combobox.jsp'
                        		           },
                        		           reader: {
                        		               type: 'json',
                        		               rootProperty: 'resultList'
                        		           }
                        		       }
                        		}),
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                },
                        	},
                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.data.StoreManager.lookup('storeb').findRecord('DTL_CD',value) !==null)
                                {
                                    return Ext.data.StoreManager.lookup('storeb').findRecord('DTL_CD',value).get('DTL_NM');
                                }
                                return value;
                            },
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 150,
                            dataIndex: 'ORIGIN',
                            text: '<span style=\'color:red\'>*</span>원산지코드',
                            editor: {
                        		id: 'originCombo',
                        		xtype: 'combobox',
                        		displayField: 'DTL_CD',
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: 'OriginStore',
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                },
                            },
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
                        	width: 150,
                        	dataIndex: 'ORIGIN_NM',
                        	text: '원산지명',
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 170,
                            dataIndex: 'GRADE',
                            text: '<span style=\'color:red\'>*</span>등급코드',
                        	editor: {
                        		id: 'gradeCombo',
                        		xtype: 'combobox',
                        		displayField: 'DTL_CD',
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: 'GradeStore',
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                },
                        	},
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
                        	width: 150,
                        	dataIndex: 'GRADE_NM',
                        	text: '등급명',
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 90,
                            dataIndex: 'LG_TYPE',
                            text: '대분류',
                            editor: {
                            	xtype: 'textfield'
                            }
//                        	editor: {
//                        		xtype: 'combobox',
//                        		displayField: 'DTL_NM',
//                        		autoLoadOnValue: true,
//                        		valueField: 'DTL_CD',
//                        		editable: false,
//                        		store: Ext.create('Ext.data.Store',{
//                        			autoLoad: true,
//                        			storeId: 'storec',
//                        			proxy: {
//                        		           type: 'ajax',
//                        		           extraParams: {
//                        		            	V_MAST_CD: 'MEAT_LG',
//                        		            	V_GRID: 'Y'
//                        		           },	
//                        		           api: {
//                        		               read: '/HSPF01/common/sql/Combobox.jsp'
//                        		           },
//                        		           reader: {
//                        		               type: 'json',
//                        		               rootProperty: 'resultList'
//                        		           }
//                        		       }
//                        		}),
//                        		listConfig: {
//                                    itemTpl: [
//                                        '<div>{DTL_NM} ({DTL_CD})</div>'
//                                    ]
//                                },
//                        	},
//                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
//                                if(Ext.data.StoreManager.lookup('storec').findRecord('DTL_CD',value) !==null)
//                                {
//                                    return Ext.data.StoreManager.lookup('storec').findRecord('DTL_CD',value).get('DTL_NM');
//                                }
//                                return value;
//                            },
                        },
                        {
                        	xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'LG_NM',
                            text: '대분류명',
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 90,
                            dataIndex: 'SM_TYPE',
                            text: '<span style=\'color:red\'>*</span>소분류',
                            blankText : '(Double Click)',
                            editor : {
                    			xtype : 'textfield',
                    			allowBlank : false,
                    			emptyText : '(Double Click)',
                    			editable : false,
                    			listeners : {
                    				afterrender : function(c) {
                    					c.getEl().on('dblclick', function() {
                    						var popup = Ext.create("Y_APPROV_DISTR.view.MyWindow");
                    						
                    						var width = Ext.getBody().getViewSize().width - 200;
                    						var height = Ext.getBody().getViewSize().height - 200;
                    						popup.setSize(width, height);
                    						popup.center();
                    						
                    						popup.show();
                    						
                    						var store = Ext.getStore('MeatStore');
                    						store.removeAll();
                    						
                    						var gridRecord = Ext.getCmp('myGrid').getSelectionModel().getSelection();
                    						Ext.getCmp('V_BF_TYPE').setValue(gridRecord[0].data['BF_TYPE']);
                    					});
                    				}
                    			}
                    		},
                        },
                        {
                        	xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 130,
                            dataIndex: 'SM_NM',
                            text: '소분류명',
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 114,
                        	dataIndex: 'ITEM_NM',
                        	text: '품목명',
                        	editor: {
                        		xtype: 'textfield'
                        	},
                        	hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 114,
                            dataIndex: 'BRAND',
                            text: '<span style=\'color:red\'>*</span>BRAND',
                        	editor: {
                        		xtype: 'textfield'
                        	}
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 114,
                            dataIndex: 'CUR',
                            text: '<span style=\'color:red\'>*</span>화폐단위',
                        	editor: {
                        		xtype: 'combobox',
                        		displayField: 'DTL_NM',
                        		autoLoadOnValue: true,
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: Ext.create('Ext.data.Store',{
                        			autoLoad: true,
                        			storeId: 'storecur',
                        			proxy: {
                        		           type: 'ajax',
                        		           extraParams: {
                        		            	V_MAST_CD: 'BA04',
                        		            	V_GRID: 'Y'
                        		           },	
                        		           api: {
                        		               read: '/HSPF01/common/sql/Combobox.jsp'
                        		           },
                        		           reader: {
                        		               type: 'json',
                        		               rootProperty: 'resultList'
                        		           }
                        		       }
                        		}),
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                }
                        	},
                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.data.StoreManager.lookup('storecur').findRecord('DTL_CD',value) !==null)
                                {
                                    return Ext.data.StoreManager.lookup('storecur').findRecord('DTL_CD',value).get('DTL_NM');
                                }
                                return value;
                            },
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            align: 'end',
                            dataIndex: 'PO_QTY',
                            text: '<span style=\'color:red\'>*</span>발주수량',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                allowExponential: false,
                                minValue: 0
                            } ,
                            summaryType: 'sum',
                            summaryRenderer: function(value, summaryData, dataIndex) {
                                return "<font color='green'>"+Ext.util.Format.number(value, '0,000.00')+"<font>"; 
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            align: 'end',
                            dataIndex: 'PO_AMT',
                            text: '<span style=\'color:red\'>*</span>발주금액',
                            summaryType: 'sum',
                            summaryRenderer: function(value, summaryData, dataIndex) {
                                return "<font color='green'>"+Ext.util.Format.number(value, '0,000.00')+"<font>"; 
                            },
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                allowExponential: false,
                            } 
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            align: 'end',
                            dataIndex: 'PO_PRC',
                            text: '단가',
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            align: 'end',
                            dataIndex: 'TAX_RT',
                            text: '<span style=\'color:red\'>*</span>관세율',
                            editor: {
                                xtype: 'numberfield',
                                allowBlank: false,
                                allowExponential: false,
                            } 
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 250,
                            dataIndex: 'USANCE_TYPE',
                            text: '<span style=\'color:red\'>*</span>USANCE조건',
                        	editor: {
                        		xtype: 'combobox',
                        		displayField: 'DTL_NM',
                        		autoLoadOnValue: true,
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: Ext.create('Ext.data.Store',{
                        			autoLoad: true,
                        			storeId: 'storee',
                        			proxy: {
                        		           type: 'ajax',
                        		           extraParams: {
                        		            	V_MAST_CD: 'USANCE',
                        		            	V_GRID: 'Y'
                        		           },	
                        		           api: {
                        		               read: '/HSPF01/common/sql/Combobox.jsp'
                        		           },
                        		           reader: {
                        		               type: 'json',
                        		               rootProperty: 'resultList'
                        		           }
                        		       }
                        		}),
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                }
                        	},
                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.data.StoreManager.lookup('storee').findRecord('DTL_CD',value) !==null)
                                {
                                    return Ext.data.StoreManager.lookup('storee').findRecord('DTL_CD',value).get('DTL_NM');
                                }
                                return value;
                            },
                        },
                        {
                        	xtype: 'numbercolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 110,
                        	align: 'end',
                        	dataIndex: 'USANCE_RT',
                        	text: '<span style=\'color:red\'>*</span>USANCE 이자율',
                        	editor: {
                        		xtype: 'numberfield',
                        		allowBlank: false,
                        		allowExponential: false,
                        	} ,
                        },
                        {
                        	xtype: 'numbercolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 110,
                        	align: 'end',
                        	dataIndex: 'LC_RT',
                        	text: '<span style=\'color:red\'>*</span>LC개설비요율',
                        	editor: {
                        		xtype: 'numberfield',
                        		allowBlank: false,
                        		allowExponential: false,
                        	} ,
                        },
                        {
                        	xtype: 'numbercolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 110,
                        	align: 'end',
                        	dataIndex: 'REC_RT',
                        	text: '<span style=\'color:red\'>*</span>인수수수료요율',
                        	editor: {
                        		xtype: 'numberfield',
                        		allowBlank: false,
                        		allowExponential: false,
                        	} ,
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 250,
                            dataIndex: 'PAY_METH',
                            text: '<span style=\'color:red\'>*</span>가격조건',
                        	editor: {
                        		xtype: 'combobox',
                        		displayField: 'DTL_NM',
                        		autoLoadOnValue: true,
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: Ext.create('Ext.data.Store',{
                        			autoLoad: true,
                        			storeId: 'storeea',
                        			proxy: {
                        		           type: 'ajax',
                        		           extraParams: {
                        		            	V_MAST_CD: 'MA04',
                        		            	V_GRID: 'Y'
                        		           },	
                        		           api: {
                        		               read: '/HSPF01/common/sql/Combobox.jsp'
                        		           },
                        		           reader: {
                        		               type: 'json',
                        		               rootProperty: 'resultList'
                        		           }
                        		       }
                        		}),
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                }
                        	},
                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.data.StoreManager.lookup('storeea').findRecord('DTL_CD',value) !==null)
                                {
                                    return Ext.data.StoreManager.lookup('storeea').findRecord('DTL_CD',value).get('DTL_NM');
                                }
                                return value;
                            },
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 100,
                        	dataIndex: 'SL_LOC',
                        	text: '창고지역',
                        	editor: {
                        		xtype: 'combobox',
                        		displayField: 'DTL_NM',
                        		autoLoadOnValue: true,
                        		valueField: 'DTL_CD',
                        		editable: false,
                        		store: Ext.create('Ext.data.Store',{
                        			autoLoad: true,
                        			storeId: 'storesloc',
                        			proxy: {
                        		           type: 'ajax',
                        		           extraParams: {
                        		            	V_MAST_CD: 'BA31',
                        		            	V_GRID: 'Y'
                        		           },	
                        		           api: {
                        		               read: '/HSPF01/common/sql/Combobox.jsp'
                        		           },
                        		           reader: {
                        		               type: 'json',
                        		               rootProperty: 'resultList'
                        		           }
                        		       }
                        		}),
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                }
                        	},
                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.data.StoreManager.lookup('storesloc').findRecord('DTL_CD',value) !==null)
                                {
                                    return Ext.data.StoreManager.lookup('storesloc').findRecord('DTL_CD',value).get('DTL_NM');
                                }
                                return value;
                            },
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            align: 'end',
                            dataIndex: 'INSUR_RT',
                            text: '<span style=\'color:red\'>*</span>보험요율',
                            format: '0,000.000',
                            editor: {
                            	xtype: 'numberfield',
                            	format: '0,000.000',
                            	forcePrecision: true,    
                            	decimalPrecision: 3    
                            },
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 150,
                        	dataIndex: 'CONT_REMARK',
                        	text: '<span style=\'color:red\'>*</span>컨테이너분류',
                        	editor: {
                        		xtype: 'textfield'
                        	}
                        },
                        {
                        	xtype: 'numbercolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 110,
                        	dataIndex: 'CONT_QTY',
                        	text: '<span style=\'color:red\'>*</span>컨테이너수량',
                        	format: '0,000',
                        	align: 'right',
                        	editor: {
                        		xtype: 'numberfield'
                        	}
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                        	width: 250,
                        	dataIndex: 'REMARK',
                        	text: '비고',
                        	editor: {
                        		xtype: 'textfield'
                        	}
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold;',
                        	width: 170,
                        	dataIndex: 'PO_NO',
                        	text: '발주번호',
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'font-size: 12px; text-align: center; font-weight: bold; ',
                        	dataIndex: 'PO_SEQ',
                        	text: '발주순번',
                        },
                    ],
                    viewConfig: {
                    	enableTextSelection: true,
                    },
                    selModel: {
                        selType: 'checkboxmodel',
                        listeners: {
                        	select: function(rowmodel, record, index, eOpts) {
                            	record.set('V_TYPE', 'V');
                            },
                            deselect: function(rowmodel, record, index, eOpts) {
                            	record.set('V_TYPE', '');
                            }
                        }
                    },
                    plugins: [
                        {
                            ptype: 'gridexporter'
                        },
                        {
                            ptype: 'clipboard'
                        },
                        {
                            ptype: 'cellediting',
                            clicksToEdit: 2,
                            listeners: {
                            	edit: function(editor, context, eOpts) {
                            		var selModel = Ext.getCmp('myGrid').getSelectionModel();
                            		selModel.select(context.record, true);
                            		
                            		var PO_QTY = context.record.get('PO_QTY'); 
                            		var PO_PRC = context.record.get('PO_PRC'); 
                            		var PO_AMT = context.record.get('PO_AMT'); 
                            		
                            		if ((context.column.dataIndex == 'PO_QTY' ||
                        				context.column.dataIndex == 'PO_AMT'	) 
                            			&& (PO_QTY != undefined) 
                            			&& (PO_AMT != undefined)) {
                            			context.record.set('PO_PRC', PO_AMT / PO_QTY);
                            		}
                            		
                            	},
                            	afteredit: function(editor, context, eOpts) {
                            		
                            		//축종
                            		if(context.column.dataIndex=='BF_TYPE') {
                            			var MAST_CD = 'ORIGIN';
                            			var V_PARAM1 = '';
                            			if(context.record.get('BF_TYPE') == 'B') { //우육
                            				V_PARAM1 = 'B';
                            			}
                        				else if(context.record.get('BF_TYPE') == 'C') { //닭
                        					V_PARAM1 = 'C';
                        					context.record.set('GRADE', 'OO');
                        					context.record.set('GRADE_NM', '-');
                            			} else if(context.record.get('BF_TYPE') == 'P') {//돈육
                            				V_PARAM1 = 'P';
                            				context.record.set('GRADE', 'OO');
                        					context.record.set('GRADE_NM', '-');
                            			}
                            			
                            			var storeOrigin = Ext.getStore('OriginStore');
                            			storeOrigin.load(
                            					{   
                            						params: 
                            						{
                            							V_MAST_CD : MAST_CD,
                            							V_PARAM1 : V_PARAM1,
                            							V_GRID: 'Y' 
                            						},
                    					});
                            			
                            			
                            			
                            			//축종이 바뀌면...
                            			if(context.value != context.originalValue) {
                            				context.record.set('ORIGIN', '');
                        					context.record.set('ORIGIN_NM', '');
                        					context.record.set('GRADE', '');
                        					context.record.set('GRADE_NM', '');
                        					context.record.set('LG_TYPE', '');
                        					context.record.set('LG_NM', '');
                        					context.record.set('SM_TYPE', '');
                        					context.record.set('SM_NM', '');
                            			} 
                            		}
                            		
                            		//원산지
                            		if(context.column.dataIndex=='ORIGIN') {
                            			
                        				var MAST_CD = '';
                        				if(context.record.get('BF_TYPE') == 'B') {//우육
                        					if(context.record.get('ORIGIN') == 'US') { //미국
                            					MAST_CD = 'BA15';
                            				} else if(context.record.get('ORIGIN') == 'AU') {//호주
                            					MAST_CD = 'BA16';
    	                        			} else if(context.record.get('ORIGIN') == 'NZ') {//뉴질랜드
    	                        				MAST_CD = 'BA17';
    	                        			}

                            				var storeGrade = Ext.getStore('GradeStore');
                            				var gradeCombo = Ext.getCmp('gradeCombo');
                            				
                            				storeGrade.load(
                    		                  {   
                    		                     params: 
                    		                         {
    	                		                    	 V_MAST_CD : MAST_CD,
    	                		                         V_GRID: 'Y' 
                    		                         },
                    		                  });
                        				} else if (context.record.get('BF_TYPE') == 'P') {//돈육
                        					if(context.record.get('ORIGIN') == 'ES') { //스페인
                        						MAST_CD = 'BA23';
                        						var storeGrade = Ext.getStore('GradeStore');
                                				var gradeCombo = Ext.getCmp('gradeCombo');
                                				
                                				storeGrade.load(
                        		                  {   
                        		                     params: 
                        		                         {
        	                		                    	 V_MAST_CD : MAST_CD,
        	                		                         V_GRID: 'Y' 
                        		                         },
                        		                  });
                        					}
                        					else{
                        						var storeGrade = Ext.getStore('GradeStore');
                        						storeGrade.removeAll();
                        					}
                        					context.record.set('GRADE', 'OO');
                        					context.record.set('GRADE_NM', '-');
                        				} else if (context.record.get('BF_TYPE') == 'C') {//계육
                        					var storeGrade = Ext.getStore('GradeStore');
                            				var gradeCombo = Ext.getCmp('gradeCombo');
                            				
                            				
                            				context.record.set('GRADE', 'OO');
                        					context.record.set('GRADE_NM', '-');
                            				storeGrade.load(
                    		                  {   
                    		                     params: 
                    		                         {
    	                		                    	 V_MAST_CD : MAST_CD,
    	                		                         V_GRID: 'Y' 
                    		                         },
                    		                  });
                        				}
                        				
                        				
                        				var storeOrigin = Ext.getStore('OriginStore');
                        				storeOrigin.each(function(rec,idx) {
                        				if(rec.get('DTL_CD') == context.record.get('ORIGIN')) {
                        					context.record.set('ORIGIN_NM', rec.get('DTL_NM'));
                        					}
                            			});
                        				
                        				//변경사항이있으면...
                        				//돈육이 아닐 때..
                            			if((context.record.get('BF_TYPE') != 'P' && context.record.get('BF_TYPE') != 'C') && (context.value != context.originalValue)) {
                        					context.record.set('GRADE', '');
                        					context.record.set('GRADE_NM', '');
                            			} 
                            		}
                            		
                            		//등급
                            		if(context.column.dataIndex=='GRADE') {
                            			var storeGrade = Ext.getStore('GradeStore');
                            			storeGrade.each(function(rec,idx) {
                            				if(rec.get('DTL_CD') == context.record.get('GRADE')) {
                            					context.record.set('GRADE_NM', rec.get('DTL_NM'))
                            				}
                            			});
                            		}
                            		

                            		var selModel = Ext.getCmp('myGrid').getSelectionModel();
                            		selModel.select(context.record, true);
                            		
                            		var PO_QTY = context.record.get('PO_QTY'); 
                            		var PO_PRC = context.record.get('PO_PRC'); 
                            		var PO_AMT = context.record.get('PO_AMT'); 
                            		
                            		if ((context.column.dataIndex == 'PO_QTY' ||
                        				context.column.dataIndex == 'PO_AMT'	) 
                            			&& (PO_QTY != undefined) 
                            			&& (PO_AMT != undefined)) {
                            			context.record.set('PO_PRC', PO_AMT / PO_QTY);
                            		}
                            		
                            	
                            		
                            	},
                            	beforeedit: function(editor, context, eOpts) {
//                            		if(context.column.dataIndex=='GRADE') {
//                            			var MAST_CD = '';
//                            			if(context.record.get('ORIGIN') == 'U') { //미국
//                            				MAST_CD = 'BA15';
//                            			} else if(context.record.get('ORIGIN') == 'A') {//호주
//                            				MAST_CD = 'BA16';
//                            			} else if(context.record.get('ORIGIN') == 'N') {//뉴질랜드
//                            				MAST_CD = 'BA17';
//                            			}
//                            			
//                            			var storeGrade = Ext.getStore('GradeStore');
//                            			var gradeCombo = Ext.getCmp('gradeCombo');
//                            			
//                            			storeGrade.load(
//                            					{   
//                            						params: 
//                            						{
//                            							V_MAST_CD : MAST_CD,
//                            							V_GRID: 'Y' 
//                            						},
//                            					});
//                            			
//                            		}
                            		
                            		//원산지
                            		if(context.column.dataIndex=='ORIGIN') {
                            			var MAST_CD = 'ORIGIN';
                            			var V_PARAM1 = '';
                            			if(context.record.get('BF_TYPE') == 'B') { //우육
                            				V_PARAM1 = 'B';
                            			} else if(context.record.get('BF_TYPE') == 'P') {//돈육
                            				V_PARAM1 = 'P';
                            			} else if(context.record.get('BF_TYPE') == 'C') {//계육
                            				V_PARAM1 = 'C';
                            			}
                            			
                            			var storeOrigin = Ext.getStore('OriginStore');
                            			storeOrigin.load(
                            					{   
                            						params: 
                            						{
                            							V_MAST_CD : MAST_CD,
                            							V_PARAM1 : V_PARAM1,
                            							V_GRID: 'Y' 
                            						},
                    					});
                            		}
                            		
                            		//등급
                            		if(context.column.dataIndex=='GRADE') {
                            			
                        				var MAST_CD = '';
                        				if(context.record.get('BF_TYPE') == 'B') {//우육
                        					if(context.record.get('ORIGIN') == 'US') { //미국
                            					MAST_CD = 'BA15';
                            				} else if(context.record.get('ORIGIN') == 'AU') {//호주
                            					MAST_CD = 'BA16';
    	                        			} else if(context.record.get('ORIGIN') == 'NZ') {//뉴질랜드
    	                        				MAST_CD = 'BA17';
    	                        			}

                            				var storeGrade = Ext.getStore('GradeStore');
                            				var gradeCombo = Ext.getCmp('gradeCombo');
                            				
                            				storeGrade.load(
                    		                  {   
                    		                     params: 
                    		                         {
    	                		                    	 V_MAST_CD : MAST_CD,
    	                		                         V_GRID: 'Y' 
                    		                         },
                    		                  });
                        				} 
                        				
                            		}
                            		
                            	}
                        	}
                        }
                    ],
                    features: [
                               {
                            	   ftype: 'summary',
                                   dock: 'bottom'
                               }
                            ],
                },
                {
                    xtype: 'splitter',
                    height: 10
                },
                {
                	id: 'myGrid1',
                    xtype: 'gridpanel',
                    flex: 1,
                    style: 'border: 1px solid lightgray; padding: 5px;',
                    header: false,
                    title: 'My Grid Panel',
                    store: 'MyStore1',
                    sortableColumns: false,
                    tbar: [
                           {
                               id: 'gridAddBtn1',
                               text: '',
                               margin: '0 3 0 0',
                               glyph: 'xf055@FontAwesome',
                               iconCls: 'grid-add-btn',
                               disabled: true
                           },
                           {
                               id: 'gridDelBtn1',
                               text: '',
                               margin: '0 3 0 0',
                               glyph: 'xf056@FontAwesome',
                               iconCls: 'grid-del-btn',
                               disabled: true
                           },
                           {
                               	id: 'gridSaveBtn1',
                               	xtype: 'button',
                               	glyph: 'xf0c7@FontAwesome',
                               	iconCls: 'grid-save-btn',
                               	margin: '0 3 0 0'
                           },
                           {
                               xtype: 'container',
                               flex: 1
                           },
                           {
                               xtype: 'button',
                               glyph: 'xf1c3@FontAwesome',
                               id: 'xlsxDown2',
                               cfg: {
                                   type: 'excel07',
                                   ext: 'xlsx'
                               },
                               iconCls: 'grid-excel-btn',
                           }
                       ],
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 40
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'V_TYPE',
                            text: 'V_TYPE',
                            hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            text: '거래단계',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    dataIndex: 'TYPE_NM',
                                    text: '구분1'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                                    dataIndex: 'COGS_NM',
                                    width: 250,
                                    text: '구분2'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 114,
                            dataIndex: 'COGS_CUR',
                            text: '화폐단위',
                        	editor: {
                        		xtype: 'combobox',
                        		displayField: 'DTL_NM',
                        		autoLoadOnValue: true,
                        		valueField: 'DTL_CD',
                        		store: Ext.create('Ext.data.Store',{
                        			autoLoad: true,
                        			storeId: 'storecur1',
                        			proxy: {
                        		           type: 'ajax',
                        		           extraParams: {
                        		            	V_MAST_CD: 'BA04',
                        		            	V_GRID: 'Y'
                        		           },	
                        		           api: {
                        		               read: '/HSPF01/common/sql/Combobox.jsp'
                        		           },
                        		           reader: {
                        		               type: 'json',
                        		               rootProperty: 'resultList'
                        		           }
                        		       }
                        		}),
                        		listConfig: {
                                    itemTpl: [
                                        '<div>{DTL_NM} ({DTL_CD})</div>'
                                    ]
                                },
                                listeners: {
                                	change: function(field, newValue, oldValue, eOpts) {
                                		var store = Ext.getStore('MyStore1');
                                		store.each(function(record, idx) {
                                			record.set('COGS_CUR', newValue);
                                		});
                                    }
                                }
                        	},
                        	renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(Ext.data.StoreManager.lookup('storecur1').findRecord('DTL_CD',value) !==null)
                                {
                                    return Ext.data.StoreManager.lookup('storecur1').findRecord('DTL_CD',value).get('DTL_NM');
                                }
                                return value;
                            },
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            align: 'end',
                            dataIndex: 'COGS_AMT',
                            text: '금액',
                            format: '0,000.00',
                            editor: {
                            	xtype: 'numberfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold; color: #3367d6',
                            width: 300,
                            dataIndex: 'REMARK',
                            text: '비고',
                            editor: {
                            	xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'AG_IN_TYPE',
                            text: '수입대행', 
                            hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'AG_IV_TYPE',
                            text: '구매대행',
                            hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'DR_IN_TYPE',
                            text: '수입',
                            hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'DR_BL_TYPE',
                            text: 'B/L양수도',
                            hidden: true
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 114,
                            dataIndex: 'DR_JI_TYPE',
                            text: '직판내수',
                            hidden: true
                        }
                    ],
                    viewConfig: {
                    	enableTextSelection: true,
                        },
                    selModel: {
                        selType: 'checkboxmodel'
                    },
                    plugins: [
                        {
                            ptype: 'gridexporter'
                        },
                        {
                            ptype: 'cellediting',
                            clicksToEdit: 1,
                        }
                    ]
                }
            ]
        }
    ]

});