/*
 * File: app/view/MyGrid.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ST_PERSON_PROFIT_LOSS.view.MyGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.myGrid',

    requires: [
        'ST_PERSON_PROFIT_LOSS.view.MyGridViewModel',
        'ST_PERSON_PROFIT_LOSS.view.MyGridViewController',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.Exporter',
        'Ext.grid.plugin.CellEditing'
    ],

    config: {
        tbar: [
            {
                id: 'gridAddBtn',
                text: '',
                margin: '0 3 0 0',
                glyph: 'xf055@FontAwesome',
                iconCls: 'grid-add-btn'
            },
            {
                id: 'gridDelBtn',
                text: '',
                margin: '0 3 0 0',
                glyph: 'xf056@FontAwesome',
                iconCls: 'grid-del-btn'
            },
            {
                id: 'calcBtn',
                text: '계산',
                margin: '0 10 0 0',
            },
            {
                xtype: 'container',
                flex: 1
            },
            {
                xtype: 'button',
                glyph: 'xf1c3@FontAwesome',
                id: 'xlsxDown',
                cfg: {
                    type: 'excel07',
                    ext: 'xlsx'
                },
                iconCls: 'grid-excel-btn',
                
            }
        ]
    },

    controller: 'mygrid',
    viewModel: {
        type: 'mygrid'
    },
    id: 'myGrid',
    style: 'border: 1px solid #659DDC; padding: 5px;',
    bodyBorder: false,
    header: false,
    store: 'MyStore',

    columns: [
        {
            xtype: 'rownumberer',
            width: 40
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            text: 'V_TYPE'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EMP_NO',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 100,
            sortable: true,
            enableTextSelection: true,
            text: '사번'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 100,
            sortable: true,
            dataIndex: 'EMP_NAME',
            enableTextSelection: true,
            text: '담당자'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 250,
            sortable: true,
            dataIndex: 'S_BP_NM',
            enableTextSelection: true,
            text: '매출처명'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 100,
            sortable: true,
            dataIndex: 'string',
            enableTextSelection: true,
            text: '코스트센터'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 150,
            sortable: true,
            dataIndex: 'LC_DOC_NO',
            enableTextSelection: true,
            text: 'L/C'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            width: 150,
            sortable: true,
            dataIndex: 'BL_DOC_NO',
            enableTextSelection: true,
            text: 'B/L'
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            sortable: true,
            enableTextSelection: true,
            text: '매출액',
            columns: [
                {
                    xtype: 'gridcolumn',
                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                    sortable: true,
                    enableTextSelection: true,
                    text: '국내',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'S_KO_BILL_QTY',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'end',
                            enableTextSelection: true,
                            exportStyle: {
                                alignment: {
                                    horizontal: 'Right'
                                }
                            },
                            text: '수량',
                            format: '0,000'
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'end',
                            dataIndex: 'S_KO_BILL_AMT',
                            enableTextSelection: true,
                            exportStyle: {
                                alignment: {
                                    horizontal: 'Right'
                                }
                            },
                            text: '금액',
                            format: '0,000'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            sortable: true,
            enableTextSelection: true,
            text: '매출원가',
            columns: [
                {
                    xtype: 'gridcolumn',
                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                    sortable: true,
                    enableTextSelection: true,
                    text: '국내',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'end',
                            dataIndex: 'S_KO_COGS_QTY',
                            enableTextSelection: true,
                            exportStyle: {
                                alignment: {
                                    horizontal: 'Right'
                                }
                            },
                            text: '수량',
                            format: '0,000'
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'end',
                            dataIndex: 'S_KO_COGS_AMT',
                            enableTextSelection: true,
                            exportStyle: {
                                alignment: {
                                    horizontal: 'Right'
                                }
                            },
                            text: '금액',
                            format: '0,000'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridcolumn',
            style: 'font-size: 12px; text-align: center; font-weight: bold;',
            sortable: true,
            enableTextSelection: true,
            text: '매출이익',
            columns: [
                {
                    xtype: 'gridcolumn',
                    style: 'font-size: 12px; text-align: center; font-weight: bold;',
                    sortable: true,
                    enableTextSelection: true,
                    text: '국내',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'end',
                            dataIndex: 'number',
                            enableTextSelection: true,
                            exportStyle: {
                                alignment: {
                                    horizontal: 'Right'
                                }
                            },
                            text: '수량',
                            format: '0,000'
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'font-size: 12px; text-align: center; font-weight: bold;',
                            width: 100,
                            align: 'end',
                            dataIndex: 'S_KO_PROFIT',
                            enableTextSelection: true,
                            exportStyle: {
                                alignment: {
                                    horizontal: 'Right'
                                }
                            },
                            text: '금액',
                            format: '0,000'
                        }
                    ]
                }
            ]
        }
    ],
    selModel: {
        selType: 'checkboxmodel',
        checkOnly: true,
        listeners: {
            select: 'onCheckboxModelSelect',
            deselect: 'onCheckboxModelDeselect'
        }
    },
    plugins: [
        {
            ptype: 'gridexporter'
        },
        {
            ptype: 'cellediting'
        }
    ]

});