/*
 * File: app/view/Popup.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Q_SUPPLIER_HSPF.view.Popup', {
    extend: 'Ext.window.Window',
    alias: 'widget.popup',

    requires: [
        'Q_SUPPLIER_HSPF.view.PopupViewModel',
        'Q_SUPPLIER_HSPF.view.TbButton1',
        'Q_SUPPLIER_HSPF.view.MySearchForm1',
        'Q_SUPPLIER_HSPF.view.MyGrid1',
        'Ext.toolbar.Toolbar',
        'Ext.form.Panel',
        'Ext.grid.Panel'
    ],

    viewModel: {
        type: 'popup'
    },
    modal: true,
    height: 650,
    width: 1000,
    title: 'popup',
    id: 'popup',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'tbbutton1'
        },
        {
            xtype: 'mysearchform1',
            modal: false
        },
        {
            xtype: 'container',
            flex: 1,
            padding: '0 10 0 10',
            layout: 'fit',
            items: [
                {
                    xtype: 'mygrid1'
                }
            ]
        }
    ]

});