/*
 * File: app/view/WinLcPop.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_L_LC_TOT_HSPF.view.WinLcPop', {
    extend: 'Ext.window.Window',
    alias: 'widget.winlcpop',

    requires: [
        'M_L_LC_TOT_HSPF.view.WinLcPopViewModel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.Exporter',
        'Ext.grid.plugin.RowEditing',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'winlcpop'
    },
    modal: true,
    height: 567,
    width: 917,
    title: 'L/C참조',
    id: 'WinLcPop',
    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            modal: true,
            shim: false,
            padding: 10,
            layout: 'center',
            items: [
                {
                    xtype: 'fieldset',
                    height: 80,
                    maxHeight: 80,
                    minHeight: 80,
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            flex: 1,
                            maxWidth: 220,
                            minWidth: 220,
                            width: 220,
                            fieldLabel: 'L/C오픈일',
                            labelWidth: 80,
                            listeners : {
                                render : function(datefield) {
                                	var nows = new Date();
                                	nows.setMonth(0);
                                	nows.setDate(1);
                                    datefield.setValue(nows);
                                }	
                            },
                            format: 'Y-m-d',
                            id: 'V_LC_DT_FR'
                        },
                        {
                            xtype: 'datefield',
                            maxWidth: 150,
                            minWidth: 150,
                            width: 150,
                            fieldLabel: '~',
                            labelWidth: 10,
                            listeners : {
                                render : function(datefield) {
                                	var nows = new Date();
                                    datefield.setValue(nows);
                                }	
                            },
                            format: 'Y-m-d',
                            id: 'V_LC_DT_TO'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 30',
                            maxWidth: 230,
                            minWidth: 230,
                            width: 230,
                            fieldLabel: '발주번호',
                            labelWidth: 80,
                            id: 'W_PO_NO',
                            name: 'lc_search'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 30',
                            maxWidth: 230,
                            minWidth: 230,
                            width: 230,
                            fieldLabel: 'L/C번호',
                            labelWidth: 80,
                            id: 'W_LC_DOC_NO',
                            name: 'lc_search'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 30',
                            maxWidth: 230,
                            minWidth: 230,
                            width: 230,
                            fieldLabel: '매입처명',
                            labelWidth: 80,
                            id: 'W_M_BP_NM_1',
                            emptyText: '(Double Click)',
                            listeners: {
                                afterrender: function(c) {
                                	c.getEl().on('dblclick', function() {
                            			var popup = Ext.create("Popup.view.WinMBpPop");
                            			popup.show();
                            			
                            			Ext.getCmp('fieldType').setValue('M_LC_DISTB_W');
                            			var store = Ext.getStore('WinMBpPopStore');
                            			store.removeAll();
                                    });
                                }
                            },
                            name: 'lc_search'
                        },
                        {
                        	xtype: 'textfield',
                        	flex: 1,
                        	margin: '0 0 0 30',
                        	maxWidth: 230,
                        	minWidth: 230,
                        	width: 230,
                        	fieldLabel: '수주처명',
                        	labelWidth: 80,
                        	id: 'W_SO_BP_NM',
                        	name: 'lc_search'
                        },
                    ]
                }
            ]
        },
        {
            xtype: 'container',
    		flex : 1,
    		layout : 'fit',
    		margin: '-20 0 0 0',
            items: [
                {
                    xtype: 'gridpanel',
                    style: 'padding: 10px;',
                    store: 'PopStore',
                    bodyBorder: false,
                    header: false,
                    
                    viewConfig: {
                    	enableTextSelection: true,
                    	getRowClass: function(record, index) {
                            var DN_QTY = record.get('DN_QTY'); 
                            var QTY = record.get('QTY'); 
                            if(DN_QTY >= QTY) {
                            	return 'bg-green'
                            }
                        },
                    },
                    tbar: [
                           {
                        	 xtype:'container',
                        	 flex: 1
                           },
                           {
                               xtype: 'button',
                               glyph: 'xf1c3@FontAwesome',
                               id: 'xlsxDown2',
                               cfg: {
                                   type: 'excel07',
                                   ext: 'xlsx'
                               },
                               iconCls: 'grid-excel-btn',
                           }
                       ],
                    id:'popGrid',
                    flex: 1,
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 40
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            text: 'V_TYPE'
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'text-align: center; font-weight: bold;',
                        	sortable: true,
                        	dataIndex: 'LC_USR_NM',
                        	enableTextSelection: true,
                        	text: '등록자',
                        	width: 100
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'text-align: center; font-weight: bold;',
                        	sortable: true,
                        	dataIndex: 'M_BP_NM',
                        	enableTextSelection: true,
                        	text: '매입처',
                        	width: 150
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'text-align: center; font-weight: bold;',
                        	sortable: true,
                        	dataIndex: 'SO_BP_NM',
                        	enableTextSelection: true,
                        	text: '수주처',
                        	width: 150
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'text-align: center; font-weight: bold;',
                            sortable: true,
                            dataIndex: 'LC_NO',
                            enableTextSelection: true,
                            text: 'L/C관리번호',
                            width: 170
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'text-align: center; font-weight: bold;',
                            sortable: true,
                            dataIndex: 'LC_DOC_NO',
                            enableTextSelection: true,
                            text: 'L/C번호',
                            width: 200
                        },
                        {
                            xtype: 'datecolumn',
                            style: 'text-align: center; font-weight: bold;',
                            align: 'center',
                            dataIndex: 'OPEN_DT',
                            enableTextSelection: true,
                            text: 'L/C오픈일',
                            format: 'Y-m-d',
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'text-align: center; font-weight: bold;',
                            sortable: true,
                            dataIndex: 'BANK_NM',
                            enableTextSelection: true,
                            text: '개설은행',
                            width: 130
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'IN_TERMS_NM',
                            style: 'text-align: center; font-weight: bold;',
                            sortable: true,
                            enableTextSelection: true,
                            text: '가격조건',
                            width: 200
                        },
                        {
                            xtype: 'gridcolumn',
                            style: 'text-align: center; font-weight: bold;',
                            sortable: true,
                            enableTextSelection: true,
                            dataIndex: 'PAY_METH_NM',
                            enableTextSelection: true,
                            text: '결제방법',
                            width: 200
                        },
                        {
                            xtype: 'numbercolumn',
                            style: 'text-align: center; font-weight: bold;',
                            align: 'end',
                            dataIndex: 'DOC_AMT',
                            enableTextSelection: true,
                            text: '개설금액',
                            format: '0,000.0000',
                            width: 150
                        },
                        {
                        	xtype: 'gridcolumn',
                        	style: 'text-align: center; font-weight: bold;',
                        	sortable: true,
                        	dataIndex: 'PO_NO',
                        	enableTextSelection: true,
                        	text: '발주번호',
                        	width: 200
                        },
                    ],
                    plugins: [
                        {
                            ptype: 'gridexporter'
                        },
                    ],
                    selModel: {
                        selType: 'checkboxmodel',
                    }
                }
            ]
        },
        {
            xtype: 'container',
            margin: '0 0 3 0',
            layout: {
                type: 'hbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    height: 30,
                    id: 'w_lcSelBtn',
                    maxHeight: 30,
                    minHeight: 30,
                    width: 100,
                    text: '조회'
                },
                {
                    xtype: 'button',
                    margins: '',
                    height: 30,
                    id: 'w_lcRegBtn',
                    margin: '0 0 0 3',
                    maxHeight: 30,
                    minHeight: 30,
                    width: 100,
                    text: '선택'
                }
            ]
        }
    ]

});