/*
 * File: app/controller/WinAddRowController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_COL_CHANGE_HSPF.controller.WinAddRowController', {
	extend : 'Ext.app.Controller',

	control : {
		"#addRowBtn" : {
			click : 'addRowBtnClick'
		}
	},

	addRowBtnClick : function(button, e, eOpts) {
		var myGrid = Ext.getCmp('myGrid').getSelection()[0];
		var store = Ext.getStore('PopStore');
		var count = store.getCount();
		var rowCount = Number(Ext.getCmp('rowCount').getValue());

		for (var i = 0; i < rowCount; i++) {
			count = count + 1;
			var rec = Ext.create('M_COL_CHANGE_HSPF.model.MyModel', {
				V_TYPE: 'I',
				MAST_DB_NO: myGrid.get('MAST_DB_NO'),
				BP_CD: myGrid.get('BP_CD'),
				BP_NM: myGrid.get('BP_NM'),
				DEPT_CD: myGrid.get('DEPT_CD'),
			});
			store.insert(count - 1, rec);
		}

		var win = Ext.WindowManager.getActive();
		if (win) {
			win.close();
		}
	}

});
