/*
 * File: app/controller/RPoRegController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('M_COLLATERAL_TOT_STATUS_HSPF.controller.WinFilePopController', {
	extend : 'Ext.app.Controller',
	stores : [ 'MyStore', 'FileStore' ],
	control : {
		"#w_fileSelBtn" : {
			click : 'w_fileSelBtnClick'
		},
		'#w_fileRegBtn' : {
			click : 'w_fileRegBtnClick'
		},
		'#fileGrid' : {
			celldblclick : 'w_fileGridDblClick'
		},
		"#fileDelBtn" : { /*파일삭제*/
        	click : 'fileDelBtnClick'
        },
		"textfield[name=col_search]" : {
			specialkey : 'tfEnter'
		}
	},

	w_fileSelBtnClick : function() {
		var fileStore = Ext.getStore('FileStore');
		fileStore.removeAll();
		fileStore.load({
			params : {
				V_TYPE : 'PS',
				V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
				V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
				V_DOC_NO : Ext.getCmp('W_DOC_NO').getValue(),
				V_DOC_TYPE_CD : Ext.getCmp('W_DOC_TYPE_CD').getValue(),
			},
			callback : function(records, operations, success) {
			}
		});

	},
	
	w_fileRegBtnClick : function() {
		var popWin = Ext.getCmp('WinFilePop');
		popWin.destroy();
	},
	
	w_fileGridDblClick : function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
		var gridObj = Ext.getCmp('fileGrid');
		var gridRecord = gridObj.getSelectionModel().getSelection();
		var V_FILE_NM = gridRecord[0].data['FILE_NM'];
		var V_FILE_IN_SYSTEM_NM = gridRecord[0].data['FILE_IN_SYSTEM_NM'];
		V_FILE_NM = encodeURI(V_FILE_NM);
		V_FILE_IN_SYSTEM_NM = encodeURI(V_FILE_IN_SYSTEM_NM);
		
		var V_DOC_NO = Ext.getCmp('W_DOC_NO').getValue();
		var V_DOC_TYPE_CD = Ext.getCmp('W_DOC_TYPE_CD').getValue();
		var V_DEPT_CD = Ext.getCmp('W_DEPT_CD').getValue();
		var V_BP_CD = Ext.getCmp('W_BP_CD').getValue();
		var V_COMP_ID = parent.Ext.getCmp('GCOMP_ID').getValue();
		var V_USR_ID = parent.Ext.getCmp('GUSER_ID').getValue();
		
		var myWin=new Ext.Window(
				{
					title : '파일다운로드',
//					html : '<iframe name="xxx" border =0 src="sql/M_COLLATERAL_TOT_STATUS_HSPF.jsp?V_TYPE=D&V_FILE_NM='+V_FILE_NM+'&V_FILE_IN_SYSTEM_NM='+V_FILE_IN_SYSTEM_NM+'" width="1%" height="1%"></iframe>',
					html : '<iframe name="xxx" border =0 src="sql/M_COLLATERAL_TOT_STATUS_HSPF.jsp?V_TYPE=P&V_DOC_NO=' + V_DOC_NO + '&V_DOC_TYPE_CD=' + V_DOC_TYPE_CD + '&V_FILE_NM='+V_FILE_NM+'&V_FILE_IN_SYSTEM_NM='+V_FILE_IN_SYSTEM_NM+'" width="1%" height="1%"></iframe>',
					width :500,
					height:500
				});
		myWin.show();
		myWin.hide();
	},
	
	/* [파일삭제] */
	fileDelBtnClick: function() {
    	var fileStore = Ext.getStore('FileStore');
    	var gridRecord = Ext.getCmp('fileGrid').getSelectionModel().getSelection();
    	
    	if(gridRecord.length > 0) {
    		Ext.MessageBox.confirm('확인', '삭제하시겠습니까?', function(btn) {
    			if(btn == 'yes') {
    				for(var i=0; i<gridRecord.length; i++) {
    		    		gridRecord[i].data['V_TYPE'] = 'PD';
    		    	}
    				
    				fileStore.sync({
    					params: {
    						V_TYPE: 'SYNC',
    						V_COMP_ID: parent.Ext.getCmp('GCOMP_ID').getValue(),
    						V_USR_ID: parent.Ext.getCmp('GUSER_ID').getValue(),
    					},
    					callback: function(records,operations,success){
    						
    						fileStore.load({
    							params : {
    								V_TYPE : 'PS',
    								V_COMP_ID : parent.Ext.getCmp('GCOMP_ID').getValue(),
    								V_USR_ID : parent.Ext.getCmp('GUSER_ID').getValue(),
    								V_DOC_NO : Ext.getCmp('W_DOC_NO').getValue(),
    								V_DOC_TYPE_CD : Ext.getCmp('W_DOC_TYPE_CD').getValue(),
    							},
    							callback : function(records, operations, success) {
    								var filePreview = '';
    			   					for(var i=0; i<records.length; i++) {
    			   						filePreview += records[i].get('FILE_NM') + '<br>';
    			   					}
    			   					
    			   					var qText = '';
    			   					if(filePreview.length == 0) {
    			   						qText = '없음';
    			   					} else {
    			   						qText = filePreview;
    			   					}
    			   					
				                	Ext.tip.QuickTipManager.register({
				                          target: 'fileAddBtn', // Target button's ID
				                          title : '<span style=\'color:#9CFFFA\'>첨부파일현황</span>',  // QuickTip Header
				                          text  : qText,
				                          dismissDelay: 10000 // Hide after 10 seconds hover
				                    });
				                	
//				                	Ext.getCmp('fileAddBtn').setText('[ ' + records.length + ' ]');
    							}
    						});
    						
						}
    				});
    			}
    		})
    	}
    	
    },

	tfEnter : function(field, e, eOpts) {
		if (e.getKey() == e.ENTER) {
			this.w_fileSelBtnClick();
		}
	}

});
