/*
 * File: app/controller/MyViewCtrl.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rawpurching.controller.MyViewCtrl', {
    extend: 'Ext.app.Controller',

    models: [
        'PurchaIngModel',
        'RawPurHeadSave'
    ],
    stores: [
        'PurchaseIngStore',
        'PurChaeCfmYnStore'
    ],
    views: [
        'MyViewport'
    ],

    control: {
        "#selectBtn": {
            click: 'selectBtnClick'
        },
        "#chgBtn": {
            click: 'onButtonClick'
        },
        "#cfmYBtn": {
            click: 'onButtonClick1'
        },
        "#grid1": {
            cellclick: 'onGridpanelCellClick'
        },
        "#cfmNBtn": {
            click: 'onButtonClick2'
        }
    },

    selectBtnClick: function(button, e, eOpts) {
        //alert('hhh');
        var store=this.getPurchaseIngStoreStore();
        var selec_check=Ext.getCmp('txtStatus').getValue();
        if (selec_check===null || selec_check==='')
            {
                Ext.Msg.alert("Warring",'진행상태는 필수입니다.');

            }
            else
                {
                   // alert(Ext.getCmp('txtItemCd').getValue().toUpperCase());

                    Ext.getCmp('gStatus').setValue(Ext.getCmp('txtStatus').getValue());
                    store.load({

                        params:{

                            //  item_cd:Ext.getCmp('txtId').getValue(),
                            bp_cd:Ext.getCmp('gBpCd').getValue().toUpperCase(),
                            bp_item_cd:Ext.getCmp('txtBpItemCd').getValue().toUpperCase(),
                            item_cd:Ext.getCmp('txtItemCd').getValue().toUpperCase(),
                            item_nm:Ext.getCmp('txtItemNm').getValue(),
                            spec:Ext.getCmp('txtSpec').getValue(),
                            maker:Ext.getCmp('txtMaker').getValue(),
                            bp_item_nm:Ext.getCmp('txtBpItemNm').getValue(),
                            s_req_no:Ext.getCmp('txtSreqNo').getValue().toUpperCase(),
                            status:Ext.getCmp('txtStatus').getValue(),
                            cmf_yn:Ext.getCmp('txtcfm').getValue().toUpperCase(),
                            dlvy_hop_dt_fr:Ext.getCmp('txtdlvyhopdtfr').getValue(),
                            dlvy_hop_dt_to:Ext.getCmp('txtdlvydthopto').getValue()

                            // bp_cd:'00004'
                            //   bp_item_cd:Ext.getCmp('txtNm').getValue(),
                            //  item_group_cd:Ext.getCmp('txtGroup').getValue()
                        }
                    });
                }
    },

    onButtonClick: function(button, e, eOpts) {

        var selec_check=Ext.getCmp('gStatus').getValue();

            if(selec_check=='A')
                {
                    var store=this.getPurchaseIngStoreStore();
                    store.sync({
                    callback : function(records,operations,success)
                         {
                             store.reload({
                                   params:{
                                        //  item_cd:Ext.getCmp('txtId').getValue(),
                                            bp_cd:Ext.getCmp('gBpCd').getValue().toUpperCase(),
                                            bp_item_cd:Ext.getCmp('txtBpItemCd').getValue().toUpperCase(),
                                            item_cd:Ext.getCmp('txtItemCd').getValue().toUpperCase(),
                                            item_nm:Ext.getCmp('txtItemNm').getValue(),
                                            spec:Ext.getCmp('txtSpec').getValue(),
                                            maker:Ext.getCmp('txtMaker').getValue(),
                                            bp_item_nm:Ext.getCmp('txtBpItemNm').getValue(),
                                            s_req_no:Ext.getCmp('txtSreqNo').getValue().toUpperCase(),
                                            status:Ext.getCmp('txtStatus').getValue(),
                                            cmf_yn:Ext.getCmp('txtcfm').getValue().toUpperCase(),
                                            dlvy_hop_dt_fr:Ext.getCmp('txtdlvyhopdtfr').getValue(),
                                            dlvy_hop_dt_to:Ext.getCmp('txtdlvydthopto').getValue()

                                        // bp_cd:'00004'
                                        //   bp_item_cd:Ext.getCmp('txtNm').getValue(),
                                        //  item_group_cd:Ext.getCmp('txtGroup').getValue()
                                    }
                             });
                             parent.Ext.getCmp(Rawpurching.app.gText).setValue('Y');
                               Ext.Msg.alert("Info",'주문변경하였습니다.');
                         }
                    });
                }
                else
                    {

                         Ext.Msg.alert("Warring",'진행상태가 주문일경우 변경 가능합니다.');
                    }

    },

    onButtonClick1: function(button, e, eOpts) {
            if (Ext.getCmp('gStatus').getValue()==='A')
                {

                       this.fnCfmYn('A');
                }
                else
                    {

                          Ext.Msg.alert("Warring",'진행상태가 주문일때 확정 됩니다..');
                    }




    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {



         if (Ext.getCmp('gStatus').getValue()==='A')
          {


                var store2=this.getPurchaseIngStoreStore();
                 var str_req_no_bs=record.get('s_req_no');


                var store2_cnt=store2.getCount();

                var check_mast=record.get('checks');

               var truefals ='';



               if (check_mast===true)
                   {
                       truefals='T';

                   }
                    else
                        {
                            truefals='F';

                        }
                        //alert(store2_cnt);
                        if (store2_cnt>0)
                            {
                                  for(var i=0;i<store2_cnt;i++)
                                  {
                                        var records=store2.getAt(i);
                                        var check=records.get('checks');


                                                var str_req_no_temp=records.get('s_req_no');



                                                if (str_req_no_bs === str_req_no_temp)
                                                    {
                                                        if (truefals==='T')
                                                            {
                                                                records.set('checks',true);
                                                            }
                                                         else
                                                             {
                                                                 records.set('checks',false);
                                                             }


                                                    }


                                  }

                            }




          }
    },

    onButtonClick2: function(button, e, eOpts) {
            if (Ext.getCmp('gStatus').getValue()==='A')
                {

                        this.fnCfmYn('C');
                }
                else
                    {

                          Ext.Msg.alert("Warring",'진행상태가 주문일때 확정 취소 됩니다..');
                    }

    },

    onLaunch: function() {
        Rawpurching.app.gText=parent.Ext.getCmp('myTab').getActiveTab().items.keys[0]; //저장체크구문


        Ext.getCmp('gBpCd').setValue(parent.Ext.getCmp('GBP_CD').getValue());
        Ext.getCmp('gUserId').setValue(parent.Ext.getCmp('GUSER_ID').getValue());
    },

    fnCfmYn: function(type) {

         var store2=this.getPurchaseIngStoreStore();
                var store2_cnt=store2.getCount();
                var store=this.getPurChaeCfmYnStoreStore();
                var nows =new Date();

                if(store2_cnt>0)
                {

                    for(var i=0;i<store2_cnt;i++)
                    {
                        var records=store2.getAt(i);  //체크 데이터 검색
                        var check=  records.get('checks');
                        var cmf_yns= records.get('cmf_yn');
                        var cruds_1='';
                        if (type==='C') // 승인 취소
                            {

                                 cruds_1='C';
                                if (cmf_yns==='Y')
                                    {
                                        cmf_yns='N';

                                    }
                            }
                            else
                                {

                                    cruds_1='A';
                                }

                        if (check===true && cmf_yns==='N')
                        {


                            store.load({
                                params:{
                                    crud:cruds_1,
                                    s_req_no:records.get('s_req_no'),
                                    bp_cd:Ext.getCmp('gBpCd').getValue(),
                                    bp_usr_id:Ext.getCmp('gUserId').getValue(),
                                    so_dt:nows,
                                    dlvy_hop_dt:records.get('dlvy_hop_dt2'),
                                    remark:'',
                                    goal_location:''
                                },
                                callback : function(records,operations,success)
                                {

                                     if (type==='A')
                                         {
                                             Ext.Msg.alert("Info",'확정하였습니다.');
                                         }
                                    else
                                        {
                                             Ext.Msg.alert("Info",'확정취소되었습니다.');
                                        }

                                    store2.load({
                                        params:{

                                                            //  item_cd:Ext.getCmp('txtId').getValue(),
                                                                bp_cd:Ext.getCmp('gBpCd').getValue().toUpperCase(),
                                                                bp_item_cd:Ext.getCmp('txtBpItemCd').getValue().toUpperCase(),
                                                                item_cd:Ext.getCmp('txtItemCd').getValue().toUpperCase(),
                                                                item_nm:Ext.getCmp('txtItemNm').getValue(),
                                                                spec:Ext.getCmp('txtSpec').getValue(),
                                                                maker:Ext.getCmp('txtMaker').getValue(),
                                                                bp_item_nm:Ext.getCmp('txtBpItemNm').getValue(),
                                                                s_req_no:Ext.getCmp('txtSreqNo').getValue().toUpperCase(),
                                                                status:Ext.getCmp('txtStatus').getValue(),
                                                                cmf_yn:Ext.getCmp('txtcfm').getValue().toUpperCase(),
                                                                dlvy_hop_dt_fr:Ext.getCmp('txtdlvyhopdtfr').getValue(),
                                                                dlvy_hop_dt_to:Ext.getCmp('txtdlvydthopto').getValue()

                                                            // bp_cd:'00004'
                                                            //   bp_item_cd:Ext.getCmp('txtNm').getValue(),
                                                            //  item_group_cd:Ext.getCmp('txtGroup').getValue()
                                                        }


                                    });

                                }

                            });
                        }
                        else
                            {
                                 if (type==='A')
                                     {
                                         Ext.Msg.alert('Warring','확정되어 있습니다.');
                                     }
                                      else
                                          {

                                              Ext.Msg.alert('Warring','확정취소되어 있습니다.');
                                          }


                            }
                    }
                }

    }

});
